In [1]:
import pandas as pd
import numpy as np
import glob

In [2]:
eQTL = pd.read_csv('/data/users2/pnadigapusuresh1/Projects/ukbiobank/Data/QTL/eQTL_hg19_1FPKM_with_rs_id.csv')

In [3]:
eQTL

,Unnamed: 0,gene_id,gene_chr,gene_start,gene_end,strand,number_of_SNPs_tested,SNP_distance_to_TSS,SNP_id,SNP_chr,SNP_start,SNP_end,nominal_pval,regression_slope,top_SNP,FDR,snps,rs_id
0,0,ENSG00000204316,chr17,73901494,73901494,+,3394,-955836,17:72945658,chr17,72945658,72945658,0.000852,0.057756,0,0.029260,72945658,rs77018335
1,1,ENSG00000204316,chr17,73901494,73901494,+,3394,-546694,17:73354800,chr17,73354800,73354800,0.001217,-0.099736,0,0.039173,73354800,rs1237746321
2,2,ENSG00000204316,chr17,73901494,73901494,+,3394,-118750,17:73782744,chr17,73782744,73782744,0.000407,-0.097620,0,0.015733,73782744,rs8077281
3,3,ENSG00000204316,chr17,73901494,73901494,+,3394,-59792,17:73841702,chr17,73841702,73841702,0.001396,-0.041055,0,0.043746,73841702,rs9900122
4,4,ENSG00000204316,chr17,73901494,73901494,+,3394,-54978,17:73846516,chr17,73846516,73846516,0.000189,-0.053441,0,0.008126,73846516,rs2004452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2120746,2120746,ENSG00000186532,chr17,1733175,1733175,+,4191,48815,17:1781990,chr17,1781990,1781990,0.000035,0.109385,0,0.001832,1781990,rs4638622
2120747,2120747,ENSG00000186532,chr17,1733175,1733175,+,4191,49967,17:1783142,chr17,1783142,1783142,0.000035,0.109502,0,0.001831,1783142,rs12948780
2120748,2120748,ENSG00000186532,chr17,1733175,1733175,+,4191,51643,17:1784818,chr17,1784818,1784818,0.000033,0.110230,0,0.001736,1784818,rs12943171
2120749,2120749,ENSG00000186532,chr17,1733175,1733175,+,4191,53551,17:1786726,chr17,1786726,1786726,0.000066,0.106669,0,0.003242,1786726,rs11872052
2120750,2120750,ENSG00000185924,chr17,1928639,1928639,+,4336,-16641,17:1911998,chr17,1911998,1911998,0.001325,0.032620,1,0.041942,1911998,rs72809519

In [7]:
eQTL.head()

,Unnamed: 0,gene_id,gene_chr,gene_start,gene_end,strand,number_of_SNPs_tested,SNP_distance_to_TSS,SNP_id,SNP_chr,SNP_start,SNP_end,nominal_pval,regression_slope,top_SNP,FDR,snps,rs_id
0,0,ENSG00000204316,chr17,73901494,73901494,+,3394,-955836,17:72945658,chr17,72945658,72945658,0.000852,0.057756,0,0.029260,72945658,rs77018335
1,1,ENSG00000204316,chr17,73901494,73901494,+,3394,-546694,17:73354800,chr17,73354800,73354800,0.001217,-0.099736,0,0.039173,73354800,rs1237746321
2,2,ENSG00000204316,chr17,73901494,73901494,+,3394,-118750,17:73782744,chr17,73782744,73782744,0.000407,-0.097620,0,0.015733,73782744,rs8077281
3,3,ENSG00000204316,chr17,73901494,73901494,+,3394,-59792,17:73841702,chr17,73841702,73841702,0.001396,-0.041055,0,0.043746,73841702,rs9900122
4,4,ENSG00000204316,chr17,73901494,73901494,+,3394,-54978,17:73846516,chr17,73846516,73846516,0.000189,-0.053441,0,0.008126,73846516,rs2004452

#### snps selected after LD pruning using 0.1 treshold

In [8]:
pruned_snps = glob.glob('*.in')

In [9]:
snps_pruned_in = [pd.read_csv(file,header=None) for file in pruned_snps]

In [10]:
all_snps_pruned_in = pd.concat(snps_pruned_in,axis=0)

In [11]:
len(eQTL[eQTL['rs_id'].isin(all_snps_pruned_in[0])]['gene_id'].unique())

12886

In [12]:
eQTL.shape

(2120751, 18)

In [13]:
np.savetxt('snp_id.txt',eQTL.SNP_id.values,fmt='%s')

In [14]:
snp_ids = eQTL.SNP_id.to_list()

In [29]:
res = map(lambda x: x.split(':')[1],snp_ids)

In [30]:
only_snp_ids = list(res)

In [31]:
eQTL['snps'] = only_snp_ids

In [11]:
ukb_snps = pd.read_csv(filepath_or_buffer='/data/users2/pnadigapusuresh1/Projects/ukbiobank/Data/ukb_cal_imggen_3_recode.raw',nrows=1,delimiter=' ')

In [12]:
len(ukb_snps.columns)

554865

In [13]:
ukb_snps.loc[:,'FID':'rs3131962_A']

       FID      IID  PAT  MAT  SEX  PHENOTYPE  rs3131962_A
0  1000293  1000293    0    0    2         -9            0

In [22]:
snp_ids_ukb = ukb_snps.columns.tolist()

In [23]:
snp_ids_ukb[1:100]

['IID',
 'PAT',
 'MAT',
 'SEX',
 'PHENOTYPE',
 'rs3131962_A',
 'rs12562034_A',
 'rs4040617_G',
 'rs79373928_G',
 'rs11240779_G',
 'rs57181708_G',
 'rs4422948_G',
 'rs4970383_A',
 'rs4970382_C',
 'rs950122_C',
 'rs6657440_C',
 'rs72631889_T',
 'rs4970459_T',
 'rs13303101_A',
 'rs192998324_G',
 'rs55678698_T',
 'rs74047407_A',
 'rs77579483_T',
 'rs1110052_G',
 'Affx-52325915_GA',
 'rs3748592_A',
 'rs3748593_A',
 'rs2272757_G',
 'rs35471880_A',
 'rs67274836_A',
 'rs114631528_A',
 'rs3748597_T',
 'rs13303065_C',
 'rs112164716_C',
 'rs13303010_G',
 'rs6696971_T',
 'rs6696609_T',
 'rs41285810_T',
 'rs3829740_G',
 'Affx-15504485_A',
 'rs3748588_T',
 'rs2340596_G',
 'rs6659460_T',
 'rs28469033_C',
 'rs28869591_T',
 'rs6677131_T',
 'rs78164078_A',
 'rs3128109_T',
 'rs35940137_A',
 'rs76233940_A',
 'Affx-15871198_A',
 'rs2799070_C',
 'rs2710890_G',
 'rs28591569_G',
 'rs28670633_T',
 'rs13303147_T',
 'rs4970349_C',
 'rs2465130_C',
 'rs138288952_A',
 'Affx-52128261_A',
 'rs2275811_C',
 'rs2710887_C',
 'rs144245019_A',
 'rs9803031_C',
 'rs113261977_T',
 'rs2799072_C',
 'rs3813193_C',
 'rs11260596_T',
 'rs4075116_C',
 'rs113592356_T',
 'rs3934834_T',
 'rs9442394_G',
 'rs115057577_G',
 'rs115723010_A',
 'rs61766340_A',
 'rs3737727_A',
 'rs116334314_A',
 'rs115662838_T',
 'rs6687776_T',
 'rs9651273_A',
 'rs11579015_C',
 'rs4970354_T',
 'rs147606383_A',
 'rs12080505_C',
 'rs61766343_T',
 'rs61766344_T',
 'rs57414802_G',
 'rs9442373_C',
 'rs55945496_A',
 'rs2298216_T',
 'rs4072537_T',
 'rs11260598_C',
 'rs113355263_A',
 'rs71628941_T',
 'rs6604971_T',
 'rs12737205_T',
 'rs116661896_A',
 'rs74045142_A',
 'rs7538773_G']

In [38]:
cd '/data/analysis/collaboration/Multi-sites_genetics/GeneticDB/GenomeBuild/human_9606_b151_GRCh37p13'

/data/analysis/collaboration/Multi-sites_genetics/GeneticDB/GenomeBuild/human_9606_b151_GRCh37p13

In [39]:
df_all = pd.read_csv('00-All_chrpos_rsid.txt',delimiter='\t\t\t',header=None)

/tmp/ipykernel_120931/3369962242.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_all = pd.read_csv('00-All_chrpos_rsid.txt',delimiter='\t\t\t',header=None)

In [40]:
df_all.head()

         0             1
0  1:10019   rs775809821
1  1:10039   rs978760828
2  1:10043  rs1008829651
3  1:10051  rs1052373574
4  1:10051  rs1326880612

In [41]:
snps = eQTL.SNP_id

In [42]:
df_all.columns = ['chr','rs']

In [43]:
df_all.head()

       chr            rs
0  1:10019   rs775809821
1  1:10039   rs978760828
2  1:10043  rs1008829651
3  1:10051  rs1052373574
4  1:10051  rs1326880612

In [44]:
df_all.set_index('chr')

                    rs
chr
1:10019    rs775809821
1:10039    rs978760828
1:10043   rs1008829651
1:10051   rs1052373574
1:10051   rs1326880612
...                ...
26:16512   rs373943637
26:16519     rs3937033
26:16526   rs386829315
26:16527   rs370705831
26:16529   rs879492040

[638388005 rows x 1 columns]

In [45]:
df_all['chr'].head()

0    1:10019
1    1:10039
2    1:10043
3    1:10051
4    1:10051
Name: chr, dtype: object

In [46]:
df_all = df_all.iloc[:615337877]

In [47]:
pd.Series(df_all.rs.values,index=df_all.chr).to_dict()

{'1:10019': 'rs775809821',
 '1:10039': 'rs978760828',
 '1:10043': 'rs1008829651',
 '1:10051': 'rs1326880612',
 '1:10055': 'rs892501864',
 '1:10063': 'rs1010989343',
 '1:10067': 'rs1489251879',
 '1:10077': 'rs1022805358',
 '1:10108': 'rs1377973775',
 '1:10109': 'rs1462685959',
 '1:10119': 'rs1156821933',
 '1:10120': 'rs1390810297',
 '1:10122': 'rs1199085795',
 '1:10128': 'rs1457723673',
 '1:10131': 'rs1289482855',
 '1:10132': 'rs1390118706',
 '1:10134': 'rs1385251551',
 '1:10135': 'rs1303755152',
 '1:10137': 'rs1346539515',
 '1:10138': 'rs1228214171',
 '1:10139': 'rs368469931',
 '1:10144': 'rs144773400',
 '1:10146': 'rs779258992',
 '1:10147': 'rs1292226269',
 '1:10149': 'rs1286868604',
 '1:10150': 'rs371194064',
 '1:10153': 'rs1331781659',
 '1:10154': 'rs1240389757',
 '1:10155': 'rs1264289758',
 '1:10156': 'rs1487252449',
 '1:10159': 'rs1211258708',
 '1:10160': 'rs1269202771',
 '1:10162': 'rs1482594023',
 '1:10163': 'rs1179689498',
 '1:10164': 'rs1413947121',
 '1:10165': 'rs796884232',
 '1:10166': 'rs1419534173',
 '1:10167': 'rs1164014856',
 '1:10168': 'rs1367957502',
 '1:10169': 'rs1456517851',
 '1:10171': 'rs1295478283',
 '1:10172': 'rs1366371903',
 '1:10173': 'rs1409475383',
 '1:10174': 'rs1306484214',
 '1:10176': 'rs1352725202',
 '1:10177': 'rs367896724',
 '1:10179': 'rs1312716213',
 '1:10180': 'rs201694901',
 '1:10181': 'rs1246412344',
 '1:10182': 'rs1408718600',
 '1:10185': 'rs1291899786',
 '1:10186': 'rs1340974825',
 '1:10188': 'rs1327557000',
 '1:10192': 'rs1202596292',
 '1:10194': 'rs1349987279',
 '1:10198': 'rs1253636590',
 '1:10199': 'rs905327004',
 '1:10200': 'rs1406296769',
 '1:10210': 'rs1480871199',
 '1:10212': 'rs1300874514',
 '1:10213': 'rs1181208913',
 '1:10217': 'rs1254048420',
 '1:10221': 'rs1344556692',
 '1:10222': 'rs1425505601',
 '1:10224': 'rs1165500808',
 '1:10227': 'rs1385944281',
 '1:10228': 'rs200462216',
 '1:10229': 'rs1167009405',
 '1:10230': 'rs775928745',
 '1:10231': 'rs200279319',
 '1:10234': 'rs145599635',
 '1:10235': 'rs1035249121',
 '1:10237': 'rs1490526935',
 '1:10241': 'rs960927773',
 '1:10244': 'rs1302754084',
 '1:10246': 'rs1377559837',
 '1:10247': 'rs1267031179',
 '1:10248': 'rs148908337',
 '1:10249': 'rs774211241',
 '1:10250': 'rs199706086',
 '1:10253': 'rs1194272037',
 '1:10254': 'rs140194106',
 '1:10255': 'rs1015259029',
 '1:10257': 'rs111200574',
 '1:10259': 'rs200940095',
 '1:10261': 'rs1276420485',
 '1:10262': 'rs1307832531',
 '1:10264': 'rs973808293',
 '1:10267': 'rs921020588',
 '1:10272': 'rs1254056895',
 '1:10273': 'rs932472638',
 '1:10276': 'rs1484153826',
 '1:10279': 'rs986614705',
 '1:10280': 'rs868542496',
 '1:10284': 'rs1184145930',
 '1:10285': 'rs866375379',
 '1:10288': 'rs1243807223',
 '1:10290': 'rs1449008465',
 '1:10291': 'rs145427775',
 '1:10293': 'rs1053005819',
 '1:10294': 'rs1186876197',
 '1:10297': 'rs868413313',
 '1:10302': 'rs865871711',
 '1:10303': 'rs1043791617',
 '1:10309': 'rs905296478',
 '1:10321': 'rs1002315756',
 '1:10327': 'rs112750067',
 '1:10328': 'rs201106462',
 '1:10329': 'rs150969722',
 '1:10330': 'rs1035171912',
 '1:10332': 'rs1175748383',
 '1:10333': 'rs1351390918',
 '1:10334': 'rs1357792689',
 '1:10336': 'rs1193008993',
 '1:10340': 'rs1471210572',
 '1:10341': 'rs1338031819',
 '1:10342': 'rs1181144652',
 '1:10347': 'rs1363828207',
 '1:10348': 'rs1384100686',
 '1:10349': 'rs1432316416',
 '1:10351': 'rs1315926476',
 '1:10352': 'rs866100747',
 '1:10353': 'rs145072688',
 '1:10354': 'rs1015856060',
 '1:10357': 'rs962371369',
 '1:10358': 'rs974158664',
 '1:10359': 'rs1218278942',
 '1:10360': 'rs1028048874',
 '1:10363': 'rs953910623',
 '1:10364': 'rs986547682',
 '1:10367': 'rs1298842584',
 '1:10370': 'rs1334634869',
 '1:10372': 'rs1313794340',
 '1:10377': 'rs1384831754',
 '1:10378': 'rs1204214557',
 '1:10383': 'rs147093981',
 '1:10387': 'rs912393906',
 '1:10389': 'rs766767872',
 '1:10390': 'rs1214126285',
 '1:10393': 'rs1287943624',
 '1:10395': 'rs1206847539',
 '1:10396': 'rs1312953559',
 '1:10400': 'rs1486139980',
 '1:10401': 'rs1243949729',
 '1:10404': 'rs1475826805',
 '1:10406': 'rs1190844716',
 '1:10409': 'rs1423489992',
 '1:10412': 'rs1481664201',
 '1:10416': 'rs1177748701',
 '1:10423': 'rs934499063',
 '1:10425': 'rs1456136931',
 '1:10428': 'rs1319638998',
 '1:10429': 'rs914488949',
 '1:10430': 'rs1345279876',
 '1:10432': 'rs1435289278',
 '1:10433': 'rs56289060',
 '1:10434': 'rs1291494374',
 '1:10437': 'rs1044101731',
 '1:10439': 'rs112766696',
 '1:10440': 'rs1239913884',
 '1:10443': 'rs938067034',
 '1:10447': 'rs1223940370',
 '1:10449': 'rs1287513526',
 '1:10450': 'rs1348884716',
 '1:10451': 'rs1326942851',
 '1:10452': 'rs1264152563',
 '1:10453': 'rs1286363400',
 '1:10454': 'rs1463012642',
 '1:10456': 'rs1447714920',
 '1:10457': 'rs1243118670',
 '1:10458': 'rs1221109143',
 '1:10459': 'rs1245244873',
 '1:10461': 'rs1490937832',
 '1:10462': 'rs1200541360',
 '1:10463': 'rs1176802610',
 '1:10466': 'rs1411691290',
 '1:10467': 'rs1471861314',
 '1:10468': 'rs1468083453',
 '1:10469': 'rs370233998',
 '1:10470': 'rs1424986436',
 '1:10471': 'rs1309260800',
 '1:10472': 'rs1238646298',
 '1:10473': 'rs1408062762',
 '1:10474': 'rs1326069208',
 '1:10475': 'rs1404283754',
 '1:10476': 'rs1321149898',
 '1:10477': 'rs1263055247',
 '1:10478': 'rs528916756',
 '1:10480': 'rs1405212621',
 '1:10482': 'rs1307108837',
 '1:10483': 'rs547662686',
 '1:10484': 'rs1431027596',
 '1:10485': 'rs1175515557',
 '1:10486': 'rs1280136053',
 '1:10487': 'rs1351457990',
 '1:10489': 'rs1227863484',
 '1:10490': 'rs565971701',
 '1:10491': 'rs1303950177',
 '1:10492': 'rs55998931',
 '1:10493': 'rs199606420',
 '1:10494': 'rs1251524062',
 '1:10497': 'rs1250176627',
 '1:10498': 'rs1338146081',
 '1:10499': 'rs1270581191',
 '1:10500': 'rs1184558895',
 '1:10503': 'rs1234015777',
 '1:10504': 'rs1472769893',
 '1:10505': 'rs548419688',
 '1:10506': 'rs568405545',
 '1:10509': 'rs1262211809',
 '1:10511': 'rs534229142',
 '1:10512': 'rs1424840445',
 '1:10513': 'rs1167640463',
 '1:10514': 'rs1429178608',
 '1:10515': 'rs1164357285',
 '1:10517': 'rs1367619635',
 '1:10518': 'rs1368469100',
 '1:10519': 'rs62636508',
 '1:10521': 'rs1384315640',
 '1:10522': 'rs1329434426',
 '1:10523': 'rs1339758319',
 '1:10526': 'rs1365181171',
 '1:10527': 'rs1246002416',
 '1:10531': 'rs1293328578',
 '1:10532': 'rs1356778175',
 '1:10533': 'rs1445779412',
 '1:10534': 'rs1486704209',
 '1:10535': 'rs1184627952',
 '1:10536': 'rs1260939575',
 '1:10539': 'rs537182016',
 '1:10542': 'rs572818783',
 '1:10543': 'rs1385151677',
 '1:10548': 'rs1346084642',
 '1:10550': 'rs1455661624',
 '1:10552': 'rs1287503569',
 '1:10555': 'rs1246979956',
 '1:10557': 'rs1274238879',
 '1:10558': 'rs1337827140',
 '1:10560': 'rs1379919052',
 '1:10563': 'rs1197872659',
 '1:10565': 'rs1274186157',
 '1:10566': 'rs868145672',
 '1:10567': 'rs940697307',
 '1:10570': 'rs1442282513',
 '1:10571': 'rs1186067446',
 '1:10572': 'rs1047520034',
 '1:10575': 'rs1244432302',
 '1:10578': 'rs887616066',
 '1:10579': 'rs538322974',
 '1:10580': 'rs1387993806',
 '1:10581': 'rs1442853137',
 '1:10582': 'rs1463224626',
 '1:10583': 'rs58108140',
 '1:10588': 'rs1401244958',
 '1:10590': 'rs1421114991',
 '1:10591': 'rs1412669807',
 '1:10592': 'rs1470537563',
 '1:10593': 'rs1338690120',
 '1:10594': 'rs1408345670',
 '1:10596': 'rs1446632268',
 '1:10597': 'rs1453531367',
 '1:10600': 'rs1298261751',
 '1:10601': 'rs1296991184',
 '1:10603': 'rs200782791',
 '1:10604': 'rs1324867574',
 '1:10609': 'rs1229891299',
 '1:10611': 'rs189107123',
 '1:10612': 'rs1441784962',
 '1:10613': 'rs1209429057',
 '1:10615': 'rs1481714525',
 '1:10616': 'rs376342519',
 '1:10617': 'rs1202326223',
 '1:10618': 'rs1265585816',
 '1:10619': 'rs1461361648',
 '1:10620': 'rs1480963373',
 '1:10621': 'rs1179100859',
 '1:10622': 'rs1427740722',
 '1:10623': 'rs1207502826',
 '1:10624': 'rs1439453463',
 '1:10627': 'rs1406482235',
 '1:10628': 'rs1281149672',
 '1:10629': 'rs1491241741',
 '1:10630': 'rs1491354133',
 '1:10633': 'rs1203196586',
 '1:10634': 'rs1251338860',
 '1:10636': 'rs1201957060',
 '1:10639': 'rs1245373687',
 '1:10641': 'rs1477959359',
 '1:10642': 'rs558604819',
 '1:10647': 'rs1168976375',
 '1:10649': 'rs1407701663',
 '1:10653': 'rs1429861185',
 '1:10654': 'rs1193520547',
 '1:10655': 'rs1365739475',
 '1:10656': 'rs1426195087',
 '1:10657': 'rs1376848026',
 '1:10658': 'rs1476940143',
 '1:10659': 'rs1178470607',
 '1:10663': 'rs1330273854',
 '1:10664': 'rs868575726',
 '1:10666': 'rs1429848064',
 '1:10667': 'rs1456667724',
 '1:10669': 'rs1359858289',
 '1:10670': 'rs1319893063',
 '1:10671': 'rs1226204851',
 '1:10674': 'rs1274023480',
 '1:10675': 'rs1382900338',
 '1:10676': 'rs1384121517',
 '1:10678': 'rs1288054092',
 '1:10681': 'rs1319305927',
 '1:10682': 'rs1451362710',
 '1:10684': 'rs1194425761',
 '1:10686': 'rs1244278434',
 '1:10687': 'rs1448208177',
 '1:10692': 'rs1187339664',
 '1:10693': 'rs867059168',
 '1:10695': 'rs1330855897',
 '1:10696': 'rs1222121318',
 '1:10698': 'rs1161245656',
 '1:10700': 'rs1389647536',
 '1:10705': 'rs1401057884',
 '1:10707': 'rs1343296943',
 '1:10711': 'rs1434325972',
 '1:10713': 'rs1296908542',
 '1:10715': 'rs1383589256',
 '1:10716': 'rs1285610967',
 '1:10719': 'rs1324850045',
 '1:10721': 'rs1355929350',
 '1:10722': 'rs1286818138',
 '1:10727': 'rs1463894888',
 '1:10734': 'rs1208624040',
 '1:10736': 'rs1462264532',
 '1:10740': 'rs1184848726',
 '1:10741': 'rs1367476021',
 '1:10745': 'rs1470313412',
 '1:10748': 'rs1160048141',
 '1:10750': 'rs1409519073',
 '1:10753': 'rs1337278095',
 '1:10754': 'rs1408296108',
 '1:10756': 'rs1454635313',
 '1:10759': 'rs1332278478',
 '1:10762': 'rs1017701292',
 '1:10763': 'rs1240055993',
 '1:10765': 'rs1327481937',
 '1:10769': 'rs1228233921',
 '1:10770': 'rs1264282854',
 '1:10774': 'rs1228328287',
 '1:10779': 'rs1198166442',
 '1:10782': 'rs1438000386',
 '1:10783': 'rs1249218724',
 '1:10784': 'rs1472140395',
 '1:10785': 'rs1176964987',
 '1:10786': 'rs1464509424',
 '1:10787': 'rs1170842917',
 '1:10788': 'rs1401555191',
 '1:10790': 'rs1392074232',
 '1:10792': 'rs1331123369',
 '1:10801': 'rs867415489',
 '1:10803': 'rs1284334878',
 '1:10804': 'rs1326230538',
 '1:10805': 'rs1231739003',
 '1:10806': 'rs1486597833',
 '1:10810': 'rs1255975963',
 '1:10811': 'rs1339439821',
 '1:10812': 'rs1197106884',
 '1:10813': 'rs1482532022',
 '1:10815': 'rs1270807885',
 '1:10816': 'rs1266288166',
 '1:10817': 'rs1489731556',
 '1:10820': 'rs1368870717',
 '1:10821': 'rs1429389790',
 '1:10828': 'rs10218492',
 '1:10832': 'rs1385494754',
 '1:10835': 'rs1301184055',
 '1:10837': 'rs1327589345',
 '1:10841': 'rs1228899387',
 '1:10846': 'rs1201262652',
 '1:10847': 'rs1429739745',
 '1:10848': 'rs1271898990',
 '1:10851': 'rs1340958514',
 '1:10854': 'rs1222740568',
 '1:10857': 'rs1487378566',
 '1:10858': 'rs1209078957',
 '1:10864': 'rs1262267892',
 '1:10869': 'rs1190553457',
 '1:10873': 'rs1388428705',
 '1:10875': 'rs1448995248',
 '1:10876': 'rs1164420911',
 '1:10880': 'rs1351904884',
 '1:10884': 'rs868423390',
 '1:10888': 'rs1293322796',
 '1:10889': 'rs1386229082',
 '1:10891': 'rs964812499',
 '1:10892': 'rs1472190396',
 '1:10904': 'rs10218493',
 '1:10905': 'rs1362131819',
 '1:10912': 'rs1319563784',
 '1:10914': 'rs1455450001',
 '1:10922': 'rs1159346308',
 '1:10923': 'rs1206722805',
 '1:10927': 'rs10218527',
 '1:10931': 'rs867393882',
 '1:10934': 'rs1403373122',
 '1:10935': 'rs1184354288',
 '1:10936': 'rs1416157845',
 '1:10938': 'rs28853987',
 '1:10942': 'rs1164457780',
 '1:10944': 'rs1459190716',
 '1:10945': 'rs1388619506',
 '1:10946': 'rs1452652925',
 '1:10947': 'rs997502321',
 '1:10953': 'rs1376463217',
 '1:10954': 'rs1227411364',
 '1:10957': 'rs1307331688',
 '1:10959': 'rs1330913810',
 '1:10960': 'rs1226422854',
 '1:10961': 'rs1267414577',
 '1:10962': 'rs1324206532',
 '1:10964': 'rs1409741497',
 '1:10967': 'rs1482345546',
 '1:10968': 'rs1181465520',
 '1:10972': 'rs1305539879',
 '1:10973': 'rs866261808',
 '1:10975': 'rs1318171998',
 '1:10978': 'rs1239075311',
 '1:10979': 'rs1470604630',
 '1:10984': 'rs1177541078',
 '1:10985': 'rs866721506',
 '1:10987': 'rs1356912132',
 '1:10990': 'rs1264382357',
 '1:11008': 'rs575272151',
 '1:11011': 'rs1352014813',
 '1:11012': 'rs544419019',
 '1:11013': 'rs1407706772',
 '1:11014': 'rs28484712',
 '1:11015': 'rs1346026541',
 '1:11019': 'rs1276464782',
 '1:11021': 'rs1310510050',
 '1:11022': 'rs28775022',
 '1:11023': 'rs1484160249',
 '1:11027': 'rs1180413726',
 '1:11030': 'rs1269317721',
 '1:11035': 'rs1480998599',
 '1:11039': 'rs1193401420',
 '1:11063': 'rs1482644816',
 '1:11065': 'rs1170550667',
 '1:11068': 'rs1175381139',
 '1:11070': 'rs1427457049',
 '1:11071': 'rs1252643349',
 '1:11072': 'rs1419625774',
 '1:11074': 'rs1438427503',
 '1:11075': 'rs1272986816',
 '1:11079': 'rs1218650108',
 '1:11081': 'rs10218495',
 '1:11082': 'rs1344521745',
 '1:11099': 'rs1203252686',
 '1:11100': 'rs1274245549',
 '1:11109': 'rs1452549560',
 '1:11125': 'rs1224319490',
 '1:11132': 'rs1245433159',
 '1:11134': 'rs1384694939',
 '1:11135': 'rs1186553109',
 '1:11154': 'rs62635278',
 '1:11157': 'rs1391507082',
 '1:11159': 'rs1447177550',
 '1:11167': 'rs62635279',
 '1:11181': 'rs1365872905',
 '1:11200': 'rs1406819182',
 '1:11202': 'rs1321341904',
 '1:11258': 'rs1349185063',
 '1:11391': 'rs75100478',
 '1:11409': 'rs9803797',
 '1:11457': 'rs2758124',
 '1:11508': 'rs3877545',
 '1:11547': 'rs113872637',
 '1:11565': 'rs2691333',
 '1:11863': 'rs187669455',
 '1:12053': 'rs111341249',
 '1:12167': 'rs112125468',
 '1:12198': 'rs62635282',
 '1:12214': 'rs202068986',
 '1:12237': 'rs1324090652',
 '1:12259': 'rs1330604035',
 '1:12266': 'rs1442951560',
 '1:12272': 'rs1281272113',
 '1:12383': 'rs62635283',
 '1:12384': 'rs748328911',
 '1:12417': 'rs1431419291',
 '1:12506': 'rs1429564191',
 '1:12522': 'rs1296825989',
 '1:12554': 'rs1371050997',
 '1:12559': 'rs1223049744',
 '1:12573': 'rs1273605438',
 '1:12586': 'rs1336625132',
 '1:12596': 'rs1211439372',
 '1:12597': 'rs1272077481',
 '1:12599': 'rs1437963543',
 '1:12603': 'rs1226365141',
 '1:12612': 'rs1205998786',
 '1:12615': 'rs1439836098',
 '1:12625': 'rs1235144565',
 '1:12629': 'rs1297131149',
 '1:12656': 'rs1299493697',
 '1:12659': 'rs1469036210',
 '1:12663': 'rs1227403403',
 '1:12664': 'rs1312228284',
 '1:12669': 'rs1360977056',
 '1:12670': 'rs1182032602',
 '1:12672': 'rs1419072050',
 '1:12673': 'rs1476353024',
 '1:12675': 'rs1288207527',
 '1:12679': 'rs1451492192',
 '1:12680': 'rs1163072234',
 '1:12693': 'rs1234796046',
 '1:12697': 'rs1463148482',
 '1:12698': 'rs1390273904',
 '1:12716': 'rs1481053922',
 '1:12719': 'rs1410641955',
 '1:12724': 'rs1241283665',
 '1:12726': 'rs1446579820',
 '1:12729': 'rs1386439422',
 '1:12732': 'rs1432922327',
 '1:12733': 'rs1319981200',
 '1:12738': 'rs1352786691',
 '1:12740': 'rs1341255098',
 '1:12745': 'rs1409167972',
 '1:12748': 'rs1293756602',
 '1:12750': 'rs1450491495',
 '1:12751': 'rs1282695040',
 '1:12752': 'rs1357144491',
 '1:12754': 'rs1231210093',
 '1:12755': 'rs1283302469',
 '1:12758': 'rs1339625912',
 '1:12762': 'rs1215868506',
 '1:12766': 'rs1354923445',
 '1:12768': 'rs1270306057',
 '1:12770': 'rs1207505138',
 '1:12773': 'rs1212472243',
 '1:12774': 'rs1297388014',
 '1:12775': 'rs1307905167',
 '1:12777': 'rs1209292926',
 '1:12778': 'rs1472789803',
 '1:12779': 'rs1261247553',
 '1:12780': 'rs1462611144',
 '1:12781': 'rs1456669983',
 '1:12782': 'rs1158017937',
 '1:12783': 'rs62635284',
 '1:12785': 'rs1332419112',
 '1:12787': 'rs1340108679',
 '1:12792': 'rs1243860065',
 '1:12795': 'rs1410749738',
 '1:12796': 'rs1290631452',
 '1:12804': 'rs1349115513',
 '1:12807': 'rs62635285',
 '1:12808': 'rs1185051244',
 '1:12811': 'rs1346498929',
 '1:12812': 'rs1422057391',
 '1:12813': 'rs1429550692',
 '1:12819': 'rs1277408515',
 '1:12826': 'rs1483183828',
 '1:12827': 'rs1184036957',
 '1:12828': 'rs1176319552',
 '1:12829': 'rs1427742506',
 '1:12832': 'rs1249379756',
 '1:12839': 'rs747124606',
 '1:12842': 'rs1472170650',
 '1:12843': 'rs1199453016',
 '1:12847': 'rs1336768104',
 '1:12851': 'rs1479014900',
 '1:12852': 'rs1344111555',
 '1:12862': 'rs1170898981',
 '1:12867': 'rs1428186115',
 '1:12868': 'rs1290303072',
 '1:12872': 'rs1310136111',
 '1:12875': 'rs1362389700',
 '1:12876': 'rs1218371393',
 '1:12882': 'rs879918139',
 '1:12888': 'rs1325545222',
 '1:12889': 'rs1302574489',
 '1:12893': 'rs1333348130',
 '1:12894': 'rs1224074355',
 '1:12901': 'rs1263808954',
 '1:12902': 'rs1316454564',
 '1:12906': 'rs1272091548',
 '1:12908': 'rs1213903993',
 '1:12914': 'rs1210225236',
 '1:12918': 'rs1269290883',
 '1:12926': 'rs1431400087',
 '1:12928': 'rs1196786772',
 '1:12930': 'rs1394531836',
 '1:12932': 'rs1244113242',
 '1:12935': 'rs1450208080',
 '1:12936': 'rs1170710654',
 '1:12938': 'rs756849893',
 '1:12940': 'rs1461751315',
 '1:12946': 'rs1294497288',
 '1:12948': 'rs1199063229',
 '1:12949': 'rs1385619950',
 '1:12951': 'rs1267247202',
 '1:12971': 'rs1481675919',
 '1:12979': 'rs1177846757',
 '1:12981': 'rs1406565589',
 '1:12985': 'rs1230063113',
 '1:12986': 'rs1398513748',
 '1:12990': 'rs1294931767',
 '1:12991': 'rs1160678173',
 '1:12992': 'rs1345350709',
 '1:12993': 'rs1403989669',
 '1:12996': 'rs1487408776',
 '1:13004': 'rs1209130011',
 '1:13006': 'rs1301014879',
 '1:13007': 'rs1190613616',
 '1:13011': 'rs574746232',
 '1:13012': 'rs1405451743',
 '1:13020': 'rs1278957536',
 '1:13023': 'rs1370542198',
 '1:13024': 'rs2462498',
 '1:13025': 'rs1222088009',
 '1:13030': 'rs1286435800',
 '1:13031': 'rs1164830225',
 '1:13035': 'rs1317700248',
 '1:13037': 'rs1436560349',
 '1:13038': 'rs1222051041',
 '1:13039': 'rs1360779033',
 '1:13041': 'rs1396229106',
 '1:13047': 'rs1314475553',
 '1:13050': 'rs1290011621',
 '1:13052': 'rs1490953354',
 '1:13053': 'rs1200770088',
 '1:13054': 'rs1268619618',
 '1:13061': 'rs1232754563',
 '1:13073': 'rs1210629232',
 '1:13074': 'rs1469060448',
 '1:13076': 'rs1485614818',
 '1:13079': 'rs1187699848',
 '1:13080': 'rs1178394265',
 '1:13082': 'rs1408105988',
 '1:13086': 'rs1423582371',
 '1:13087': 'rs1344056658',
 '1:13091': 'rs1466161089',
 '1:13095': 'rs1304207847',
 '1:13105': 'rs1376531494',
 '1:13108': 'rs1413870547',
 '1:13110': 'rs540538026',
 '1:13111': 'rs74924349',
 '1:13115': 'rs1367204845',
 '1:13116': 'rs62635286',
 '1:13118': 'rs62028691',
 '1:13121': 'rs1333841087',
 '1:13127': 'rs1444329965',
 '1:13138': 'rs12239753',
 '1:13140': 'rs1316409991',
 '1:13141': 'rs1281303939',
 '1:13143': 'rs1377802774',
 '1:13146': 'rs1482415811',
 '1:13148': 'rs1210551146',
 '1:13149': 'rs1245477665',
 '1:13151': 'rs1313270350',
 '1:13153': 'rs1362019844',
 '1:13154': 'rs2691331',
 '1:13156': 'rs552314247',
 '1:13158': 'rs12239425',
 '1:13160': 'rs12239277',
 '1:13161': 'rs1177606205',
 '1:13162': 'rs1357034463',
 '1:13166': 'rs1272787723',
 '1:13168': 'rs1433742695',
 '1:13169': 'rs1436530583',
 '1:13172': 'rs1207307752',
 '1:13173': 'rs1407839502',
 '1:13175': 'rs1278871319',
 '1:13176': 'rs1232922756',
 '1:13177': 'rs1443554704',
 '1:13178': 'rs1181355646',
 '1:13181': 'rs1386646947',
 '1:13185': 'rs1210401264',
 '1:13187': 'rs1444868184',
 '1:13193': 'rs1484231356',
 '1:13195': 'rs1232739374',
 '1:13196': 'rs1489112721',
 '1:13197': 'rs1192382122',
 '1:13199': 'rs1422423980',
 '1:13203': 'rs1453315839',
 '1:13213': 'rs1391697168',
 '1:13214': 'rs1167065236',
 '1:13216': 'rs879765206',
 '1:13217': 'rs1411569304',
 '1:13221': 'rs1329501114',
 '1:13224': 'rs1401113893',
 '1:13227': 'rs1291754897',
 '1:13228': 'rs1452078127',
 '1:13230': 'rs1313023331',
 '1:13233': 'rs1344585990',
 '1:13234': 'rs1385218634',
 '1:13242': 'rs1213134468',
 '1:13244': 'rs1245832290',
 '1:13248': 'rs1269959092',
 '1:13250': 'rs1224388578',
 '1:13255': 'rs1200488492',
 '1:13257': 'rs1467633325',
 '1:13259': 'rs562993331',
 '1:13267': 'rs1216827187',
 '1:13270': 'rs1259334834',
 '1:13271': 'rs1461275052',
 '1:13272': 'rs1414208639',
 '1:13273': 'rs531730856',
 '1:13275': 'rs1244477464',
 '1:13279': 'rs1162577960',
 '1:13281': 'rs78406944',
 '1:13283': 'rs1192086427',
 '1:13284': 'rs548333521',
 '1:13285': 'rs1476307529',
 '1:13286': 'rs1168408523',
 '1:13289': 'rs538791886',
 '1:13290': 'rs1357492815',
 '1:13292': 'rs1230448710',
 '1:13293': 'rs1334774778',
 '1:13298': 'rs1208770165',
 '1:13302': 'rs75241669',
 '1:13303': 'rs1468199879',

In [49]:
d = _

In [50]:
eQTL.SNP_id.map(d)

0            rs77018335
1          rs1237746321
2             rs8077281
3             rs9900122
4             rs2004452
               ...
2120746       rs4638622
2120747      rs12948780
2120748      rs12943171
2120749      rs11872052
2120750      rs72809519
Name: SNP_id, Length: 2120751, dtype: object

In [51]:
snps = _

In [53]:
eQTL['rs_id'] = snps.values

### Saving the eQTL with their rs_id

In [ ]:
eQTL.to_csv('./eQTL_hg19_1FPKM_with_rs_id.csv')

In [18]:
snps.to_csv('rs_snps_eqtl.txt',index=True)

In [36]:
snps = pd.read_csv('./rs_snps_eqtl.txt')

In [8]:
final_snps = pd.read_csv('../ukb_cal_imggen_eQTL_matched_recode.raw',delim_whitespace=True,nrows=3)

In [9]:
final_snps.shape

(3, 28654)

In [10]:
final_snps.columns

Index(['FID', 'IID', 'PAT', 'MAT', 'SEX', 'PHENOTYPE', 'rs3128109_T',
       'rs4970349_C', 'rs2799072_C', 'rs11260596_T',
       ...
       'rs6151416_A', 'rs5770964_G', 'rs117063829_T', 'rs6010045_T',
       'rs36006314_G', 'rs2157711_C', 'rs5770821_G', 'rs78342408_T',
       'rs56207913_T', 'rs73174437_T'],
      dtype='object', length=28654)

In [2]:
for i in range(1,23):
    print(f'ukb_imputed_imggen_chr{i}')

ukb_imputed_imggen_chr1
ukb_imputed_imggen_chr2
ukb_imputed_imggen_chr3
ukb_imputed_imggen_chr4
ukb_imputed_imggen_chr5
ukb_imputed_imggen_chr6
ukb_imputed_imggen_chr7
ukb_imputed_imggen_chr8
ukb_imputed_imggen_chr9
ukb_imputed_imggen_chr10
ukb_imputed_imggen_chr11
ukb_imputed_imggen_chr12
ukb_imputed_imggen_chr13
ukb_imputed_imggen_chr14
ukb_imputed_imggen_chr15
ukb_imputed_imggen_chr16
ukb_imputed_imggen_chr17
ukb_imputed_imggen_chr18
ukb_imputed_imggen_chr19
ukb_imputed_imggen_chr20
ukb_imputed_imggen_chr21
ukb_imputed_imggen_chr22

## Creating the ADJ matrices

In [4]:
import glob

In [5]:
csv_flies = glob.glob('/data/users2/pnadigapusuresh1/Projects/ukbiobank/Data/QTL'+'/*pruned_recoded.raw')

In [6]:
df_list = [pd.read_csv(file,sep=' ',nrows=3,index_col='FID',usecols=lambda x: x not in ['PHENOTYPE','SEX','IID','PAT','MAT']) for file in csv_flies]

In [7]:
df_list[20].iloc[:,:10]

,rs13437666_C,rs79146206_G,rs6964562_C,rs4593475_C,rs6968087_A,rs28378990_A,rs6945181_A,rs148955469_G,rs117084377_C,rs75418879_T
FID,,,,,,,,,,
1767364,0,0,2,2,0,0,1,0,0,0
2268235,0,0,2,2,1,1,0,0,0,0
4521147,0,0,0,0,0,0,1,0,0,0

In [8]:
big_df = pd.concat(df_list,axis=1)

In [9]:
big_df.shape

(3, 37606)

In [10]:
big_df.iloc[:,:10]

,rs77114150_A,rs36020100_A,rs28648766_T,rs441438_C,rs331007_G,rs61614253_A,rs7225407_A,rs115874046_A,rs1570000_C,rs78300101_C
FID,,,,,,,,,,
1767364,0,2,0,1,1,0,1,0,0,0
2268235,0,1,0,1,2,0,0,1,0,0
4521147,0,0,0,0,1,0,0,0,0,0

In [11]:
final_snps = big_df.columns.tolist()

In [12]:
final_snps = list(map(lambda snp: snp.split('_')[0],final_snps))

In [13]:
final_eqtls = eQTL[eQTL['rs_id'].isin(final_snps)]

In [14]:
final_eqtls

,Unnamed: 0,gene_id,gene_chr,gene_start,gene_end,strand,number_of_SNPs_tested,SNP_distance_to_TSS,SNP_id,SNP_chr,SNP_start,SNP_end,nominal_pval,regression_slope,top_SNP,FDR,snps,rs_id
33,33,ENSG00000204316,chr17,73901494,73901494,+,3394,40702,17:73942196,chr17,73942196,73942196,3.908310e-05,0.131688,0,2.023840e-03,73942196,rs71382188
41,41,ENSG00000188878,chr17,73937119,73937119,+,3477,-776304,17:73160815,chr17,73160815,73160815,4.038930e-05,0.346087,0,2.084354e-03,73160815,rs138046159
120,120,ENSG00000257949,chr17,73975301,73975301,+,3544,11913,17:73987214,chr17,73987214,73987214,1.004390e-09,-0.352123,0,1.132131e-07,73987214,rs139824587
136,136,ENSG00000257949,chr17,73975301,73975301,+,3544,34766,17:74010067,chr17,74010067,74010067,5.757640e-06,-0.429004,0,3.586709e-04,74010067,rs112572575
137,137,ENSG00000257949,chr17,73975301,73975301,+,3544,34971,17:74010272,chr17,74010272,74010272,4.869350e-11,0.126632,0,6.435118e-09,74010272,rs2598420
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2120601,2120601,ENSG00000132386,chr17,1665253,1665253,+,4233,658410,17:2323663,chr17,2323663,2323663,7.486830e-04,-0.308176,0,2.627355e-02,2323663,rs61753102
2120610,2120610,ENSG00000132383,chr17,1732996,1732996,+,4194,-429894,17:1303102,chr17,1303102,1303102,6.912490e-04,-0.134710,0,2.458446e-02,1303102,rs35172388
2120696,2120696,ENSG00000132383,chr17,1732996,1732996,+,4194,67221,17:1800217,chr17,1800217,1800217,3.102950e-09,-0.104906,1,3.282862e-07,1800217,rs7406062
2120702,2120702,ENSG00000186532,chr17,1733175,1733175,+,4191,-774661,17:958514,chr17,958514,958514,5.168770e-04,-0.115433,0,1.925770e-02,958514,rs2261299
2120750,2120750,ENSG00000185924,chr17,1928639,1928639,+,4336,-16641,17:1911998,chr17,1911998,1911998,1.324730e-03,0.032620,1,4.194184e-02,1911998,rs72809519

In [15]:
len(final_eqtls['gene_id'].unique())

12886

In [16]:
len(final_eqtls['SNP_id'].unique())

37470

In [17]:
final_eqtls.groupby(['SNP_id','gene_id']).size()

SNP_id        gene_id
10:100020572  ENSG00000166024    1
10:100041538  ENSG00000119943    1
              ENSG00000155265    1
10:100045000  ENSG00000171160    1
10:100075076  ENSG00000119943    1
                                ..
9:99983931    ENSG00000188801    1
              ENSG00000203279    1
              ENSG00000213612    1
              ENSG00000228038    1
              ENSG00000255036    1
Length: 45455, dtype: int64

In [18]:
final_eqtls[final_eqtls.duplicated(['SNP_id'])]

,Unnamed: 0,gene_id,gene_chr,gene_start,gene_end,strand,number_of_SNPs_tested,SNP_distance_to_TSS,SNP_id,SNP_chr,SNP_start,SNP_end,nominal_pval,regression_slope,top_SNP,FDR,snps,rs_id
293,293,ENSG00000167881,chr17,74068734,74068734,+,3651,22456,17:74091190,chr17,74091190,74091190,1.695810e-07,0.051636,0,1.393950e-05,74091190,rs7212071
333,333,ENSG00000182473,chr17,74079095,74079095,+,3682,12095,17:74091190,chr17,74091190,74091190,2.126470e-05,0.065754,0,1.171846e-03,74091190,rs7212071
525,525,ENSG00000129646,chr17,74303761,74303761,+,3881,-316547,17:73987214,chr17,73987214,73987214,3.664650e-08,-0.307343,0,3.343890e-06,73987214,rs139824587
567,567,ENSG00000129646,chr17,74303761,74303761,+,3881,-53755,17:74250006,chr17,74250006,74250006,1.227960e-15,-0.143533,0,2.521036e-13,74250006,rs8071545
581,581,ENSG00000129646,chr17,74303761,74303761,+,3881,-32903,17:74270858,chr17,74270858,74270858,2.711150e-07,-0.201246,0,2.156326e-05,74270858,rs74808805
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2120417,2120417,ENSG00000167703,chr17,1532130,1532130,+,4345,925514,17:2457644,chr17,2457644,2457644,9.269000e-04,0.202301,0,3.135794e-02,2457644,rs117297421
2120441,2120441,ENSG00000074660,chr17,1549041,1549041,+,4332,729603,17:2278644,chr17,2278644,2278644,7.940860e-07,-0.103760,1,5.829612e-05,2278644,rs2252910
2120449,2120449,ENSG00000167705,chr17,1552326,1552326,+,4334,-195682,17:1356644,chr17,1356644,1356644,1.609350e-03,0.144334,0,4.902310e-02,1356644,rs117985867
2120586,2120586,ENSG00000132386,chr17,1665253,1665253,+,4233,66344,17:1731597,chr17,1731597,1731597,1.507050e-04,0.349130,0,6.673966e-03,1731597,rs140729163
2120595,2120595,ENSG00000132386,chr17,1665253,1665253,+,4233,135696,17:1800949,chr17,1800949,1800949,2.987730e-09,0.150302,0,3.167279e-07,1800949,rs3744766

#### Loading Alzhiemers protien ID's

In [19]:
p_g = pd.read_csv('/data/users2/pnadigapusuresh1/Projects/ukbiobank/bio_informed_nn/gProfiler_hsapiens_6-20-2023_4-00-56 PM.csv')

In [20]:
p_g.columns

Index(['initial_alias', 'converted_alias', 'name', 'description', 'namespace'], dtype='object')

In [21]:
p_g_new = p_g.drop_duplicates(subset=['initial_alias','converted_alias'])

In [22]:
p_g_new

,initial_alias,converted_alias,name,description,namespace
0,P05067,ENSG00000142192,APP,amyloid beta precursor protein [Source:HGNC Sy...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
30,P49768,ENSG00000080815,PSEN1,presenilin 1 [Source:HGNC Symbol;Acc:HGNC:9508],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
104,P54253,ENSG00000124788,ATXN1,ataxin 1 [Source:HGNC Symbol;Acc:HGNC:10548],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
151,P42858,ENSG00000197386,HTT,huntingtin [Source:HGNC Symbol;Acc:HGNC:4851],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
270,O14672,ENSG00000137845,ADAM10,ADAM metallopeptidase domain 10 [Source:HGNC S...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
...,...,...,...,...,...
3237,P43116,ENSG00000125384,PTGER2,prostaglandin E receptor 2 [Source:HGNC Symbol...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
3245,P53805,ENSG00000159200,RCAN1,regulator of calcineurin 1 [Source:HGNC Symbol...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
3264,Q96L34,ENSG00000007047,MARK4,microtubule affinity regulating kinase 4 [Sour...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
3269,Q7KZI7,ENSG00000072518,MARK2,microtubule affinity regulating kinase 2 [Sour...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
3271,Q9P0L2,ENSG00000116141,MARK1,microtubule affinity regulating kinase 1 [Sour...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"

In [23]:
len(p_g_new['converted_alias'].unique())

214

In [24]:
alzhimers_gene_id = p_g_new['converted_alias'].unique().tolist()

#### Matching final_eqtl gene_id with the alzhiemer's gene id

In [161]:
first_second_level_genes = final_eqtls[final_eqtls['gene_id'].isin(alzhimers_gene_id)]

In [162]:
first_second_level_genes

,Unnamed: 0,gene_id,gene_chr,gene_start,gene_end,strand,number_of_SNPs_tested,SNP_distance_to_TSS,SNP_id,SNP_chr,SNP_start,SNP_end,nominal_pval,regression_slope,top_SNP,FDR,snps,rs_id
19254,19254,ENSG00000175582,chr11,73472182,73472182,+,3320,115671,11:73587853,chr11,73587853,73587853,0.000721,-0.168627,0,0.025454,73587853,rs76332820
19308,19308,ENSG00000175582,chr11,73472182,73472182,+,3320,233082,11:73705264,chr11,73705264,73705264,0.000071,0.061784,0,0.003427,73705264,rs4944873
21876,21876,ENSG00000137486,chr11,75062749,75062749,+,3105,-654643,11:74408106,chr11,74408106,74408106,0.001491,-0.091301,0,0.046117,74408106,rs7131683
21957,21957,ENSG00000149243,chr11,75141236,75141236,+,3064,-95693,11:75045543,chr11,75045543,75045543,0.000402,0.225383,0,0.015567,75045543,rs139848901
22000,22000,ENSG00000149243,chr11,75141236,75141236,+,3064,-14506,11:75126730,chr11,75126730,75126730,0.000296,0.054877,0,0.011975,75126730,rs10793118
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111780,2111780,ENSG00000175166,chr3,184016497,184016497,+,4337,-174724,3:183841773,chr3,183841773,183841773,0.000086,0.167709,0,0.004072,183841773,rs77980659
2111782,2111782,ENSG00000175166,chr3,184016497,184016497,+,4337,-77640,3:183938857,chr3,183938857,183938857,0.000948,-0.038527,0,0.031945,183938857,rs4447797
2111785,2111785,ENSG00000175166,chr3,184016497,184016497,+,4337,11042,3:184027539,chr3,184027539,184027539,0.000002,-0.056150,1,0.000106,184027539,rs13062950
2111788,2111788,ENSG00000175166,chr3,184016497,184016497,+,4337,69239,3:184085736,chr3,184085736,184085736,0.001154,-0.071793,0,0.037505,184085736,rs9839511
2111791,2111791,ENSG00000175166,chr3,184016497,184016497,+,4337,350532,3:184367029,chr3,184367029,184367029,0.000443,0.102622,0,0.016906,184367029,rs145914525

In [163]:
second_level_matched_genes = first_second_level_genes['gene_id'].unique().tolist()

In [164]:
len(second_level_matched_genes)

133

##### First level SNPs and 2nd level Genes

In [165]:
len(first_second_level_genes['SNP_id'].tolist())

401

In [166]:
first_second_level_genes[first_second_level_genes['SNP_id'].duplicated()]

,Unnamed: 0,gene_id,gene_chr,gene_start,gene_end,strand,number_of_SNPs_tested,SNP_distance_to_TSS,SNP_id,SNP_chr,SNP_start,SNP_end,nominal_pval,regression_slope,top_SNP,FDR,snps,rs_id
1537290,1537290,ENSG00000177697,chr11,832843,832843,+,3978,209124,11:1041967,chr11,1041967,1041967,0.000017,-0.071387,0,0.000972,1041967,rs72842424

In [167]:
first_second_level_genes[first_second_level_genes['SNP_id'] == '11:1041967']

,Unnamed: 0,gene_id,gene_chr,gene_start,gene_end,strand,number_of_SNPs_tested,SNP_distance_to_TSS,SNP_id,SNP_chr,SNP_start,SNP_end,nominal_pval,regression_slope,top_SNP,FDR,snps,rs_id
1466290,1466290,ENSG00000023191,chr11,503570,503570,+,3113,538397,11:1041967,chr11,1041967,1041967,0.000501,0.049051,0,0.018756,1041967,rs72842424
1537290,1537290,ENSG00000177697,chr11,832843,832843,+,3978,209124,11:1041967,chr11,1041967,1041967,0.000017,-0.071387,0,0.000972,1041967,rs72842424

In [172]:
adj_matrix_first_second = pd.crosstab(first_second_level_genes['SNP_id'],first_second_level_genes['gene_id'])

In [173]:
adj_matrix_first_second.shape

(400, 133)

In [57]:
with open('first_second_adj_matrix.npy','wb') as f:
    np.save(f, adj_matrix_first_second.to_numpy())

#### Mstching these matched genes between eqtl's and alzhiemers genes for third level connections

In [174]:
gene_dataset = pd.read_csv('2023-06-16-10-44.txt',delimiter='\t')

In [175]:
gene_dataset

,# ID(s) interactor A,ID(s) interactor B,Alt. ID(s) interactor A,Alt. ID(s) interactor B,Alias(es) interactor A,Alias(es) interactor B,Interaction detection method(s),Publication 1st author(s),Publication Identifier(s),Taxid interactor A,Taxid interactor B,Interaction type(s),Source database(s),Interaction identifier(s),Confidence value(s)
0,uniprotkb:P05067,uniprotkb:O95864,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:A8K2M6|uniprotkb:Q6MZQ7|uniprotkb:Q9...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,psi-mi:fads2_human(display_short)|psi-mi:Acyl-...,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Hosp F. et al.(2015),intact:EBI-21132292|pubmed:25959826|imex:IM-27137,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0486""(UniProt)",intact:EBI-21132574|imex:IM-27137-1,-
1,uniprotkb:P05067,uniprotkb:P13861,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:Q16823|intact:EBI-6116682|uniprotkb:...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,psi-mi:kap2_human(display_short)|psi-mi:cAMP-d...,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Hosp F. et al.(2015),intact:EBI-21132292|pubmed:25959826|imex:IM-27137,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0486""(UniProt)",intact:EBI-21132574|imex:IM-27137-1,-
2,uniprotkb:P05067,uniprotkb:Q8TD31,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:Q9NRK8|uniprotkb:Q9NWY9|uniprotkb:Q9...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,psi-mi:cchcr_human(display_short)|psi-mi:Coile...,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Hosp F. et al.(2015),intact:EBI-21132292|pubmed:25959826|imex:IM-27137,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0486""(UniProt)",intact:EBI-21132574|imex:IM-27137-1,-
3,uniprotkb:P05067,uniprotkb:Q15392,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:D3DQ51|uniprotkb:Q9HBA8|uniprotkb:B7...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,"psi-mi:dhc24_human(display_short)|psi-mi:""Delt...","psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Hosp F. et al.(2015),intact:EBI-21132292|pubmed:25959826|imex:IM-27137,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0486""(UniProt)",intact:EBI-21132574|imex:IM-27137-1,-
4,uniprotkb:P05067,uniprotkb:Q15125,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:Q6IBI9|uniprotkb:Q6FGL3|ensembl:ENSP...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,"psi-mi:ebp_human(display_short)|psi-mi:""3-beta...","psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Hosp F. et al.(2015),intact:EBI-21132292|pubmed:25959826|imex:IM-27137,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0486""(UniProt)",intact:EBI-21132574|imex:IM-27137-1,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,uniprotkb:P05067,uniprotkb:P63104,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:P29213|uniprotkb:P29312|uniprotkb:Q3...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,psi-mi:1433z_human(display_short)|psi-mi:14-3-...,"psi-mi:""MI:0006""(anti bait coimmunoprecipitation)",Cottrell BA. et al.(2005),intact:EBI-1993060|pubmed:16049941|imex:IM-20090,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0469""(European Bioinformatics Insti...",intact:EBI-960318|imex:IM-20090-2,-
2396,uniprotkb:P05067,uniprotkb:P07900,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,intact:EBI-1642144|uniprotkb:Q2PP14|ensembl:EN...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,psi-mi:hs90a_human(display_short)|psi-mi:Heat ...,"psi-mi:""MI:0006""(anti bait coimmunoprecipitation)",Cottrell BA. et al.(2005),intact:EBI-1993060|pubmed:16049941|imex:IM-20090,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0469""(European Bioinformatics Insti...",intact:EBI-960318|imex:IM-20090-2,-
2397,uniprotkb:P05067,uniprotkb:P46459,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:Q8N6D7|uniprotkb:Q9UKZ2|uniprotkb:A8...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,psi-mi:nsf_human(display_short)|psi-mi:Vesicle...,"psi-mi:""MI:0006""(anti bait coimmunoprecipitation)",Cottrell BA. et al.(2005),intact:EBI-1993060|pubmed:16049941|imex:IM-20090,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0469""(European Bioinformatics Insti...",intact:EBI-960318|imex:IM-20090-2,-
2398,uniprotkb:P10636,uniprotkb:P27448,uniprotkb:P18518|uniprotkb:Q14799|uniprotkb:Q1...,uniprotkb:O60219|uniprotkb:Q8TB41|uniprotkb:Q8...,psi-mi:tau_human(display_short)|psi-mi:Microtu...,psi-mi:mark3_human(display_short)|psi-mi:MAP/m...,"psi-mi:""MI:0813""(proximity ligation assay)",Gu G.J. et al.(2013),intact:EBI-9699845|pubmed:23666762|imex:IM-23074,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:2364""(proximity)","psi-mi:""MI:0469""(European Bioinformatics Insti...",intact:EBI-9700143|imex:IM-23074-5,-
2399,uniprotkb:P05067,uniprotkb:Q05193,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:A6NLM6|uniprotkb:Q5SYX0|uniprotkb:Q5...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,psi-mi:dyn1_human(display_short)|psi-mi:Dynami...,"psi-mi:""MI:0006""(anti bait coimmunoprecipitation)",Cottrell BA. et al.(2005),intact:EBI-1993060|pubmed:16049941|imex:IM-20090,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0469""(European Bioinformatics Insti...",intact:EBI-960318|imex:IM-20090-2,-

In [176]:
gene_dataset['Interactor A P_id'] = list(map(lambda x: (x.split(':')[1]).split('-')[0], gene_dataset['# ID(s) interactor A'].tolist()))

In [33]:
first_second_level_matched_genes =  p_g_new[p_g_new['converted_alias'].isin(second_level_matched_genes)]

In [148]:
first_second_level_matched_genes

,initial_alias,converted_alias,name,description,namespace
0,P05067,ENSG00000142192,APP,amyloid beta precursor protein [Source:HGNC Sy...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
30,P49768,ENSG00000080815,PSEN1,presenilin 1 [Source:HGNC Symbol;Acc:HGNC:9508],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
104,P54253,ENSG00000124788,ATXN1,ataxin 1 [Source:HGNC Symbol;Acc:HGNC:10548],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
151,P42858,ENSG00000197386,HTT,huntingtin [Source:HGNC Symbol;Acc:HGNC:4851],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
270,O14672,ENSG00000137845,ADAM10,ADAM metallopeptidase domain 10 [Source:HGNC S...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
...,...,...,...,...,...
3220,Q02410,ENSG00000107282,APBA1,amyloid beta precursor protein binding family ...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
3225,P49407,ENSG00000137486,ARRB1,arrestin beta 1 [Source:HGNC Symbol;Acc:HGNC:711],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
3235,P32121,ENSG00000141480,ARRB2,arrestin beta 2 [Source:HGNC Symbol;Acc:HGNC:712],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
3245,P53805,ENSG00000159200,RCAN1,regulator of calcineurin 1 [Source:HGNC Symbol...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
3264,Q96L34,ENSG00000007047,MARK4,microtubule affinity regulating kinase 4 [Sour...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"

In [149]:
first_second_level_matched_genes_list = first_second_level_matched_genes['initial_alias'].unique().tolist()

In [189]:
first_second_level_matched_ens_list = first_second_level_matched_genes['converted_alias'].unique().tolist()

In [171]:
len(first_second_level_matched_genes['converted_alias'].unique().tolist())

133

In [153]:
len(first_second_level_matched_genes_list)

131

##### 2 genes of first_secong level matched genes (133) are missing in gene dataset

In [180]:
first_second_level_matched_genes.head()

,initial_alias,converted_alias,name,description,namespace
0,P05067,ENSG00000142192,APP,amyloid beta precursor protein [Source:HGNC Sy...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
30,P49768,ENSG00000080815,PSEN1,presenilin 1 [Source:HGNC Symbol;Acc:HGNC:9508],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
104,P54253,ENSG00000124788,ATXN1,ataxin 1 [Source:HGNC Symbol;Acc:HGNC:10548],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
151,P42858,ENSG00000197386,HTT,huntingtin [Source:HGNC Symbol;Acc:HGNC:4851],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
270,O14672,ENSG00000137845,ADAM10,ADAM metallopeptidase domain 10 [Source:HGNC S...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"

In [183]:
gene_dataset['initial_alias'] = gene_dataset['Interactor A P_id']

In [187]:
gene_dataset_with_ens = gene_dataset.join(first_second_level_matched_genes[['initial_alias','converted_alias']].set_index('initial_alias'),on='initial_alias')

In [190]:
gene_dataset_with_ens.head()

,# ID(s) interactor A,ID(s) interactor B,Alt. ID(s) interactor A,Alt. ID(s) interactor B,Alias(es) interactor A,Alias(es) interactor B,Interaction detection method(s),Publication 1st author(s),Publication Identifier(s),Taxid interactor A,Taxid interactor B,Interaction type(s),Source database(s),Interaction identifier(s),Confidence value(s),Interactor A P_id,initial_alias,converted_alias
0,uniprotkb:P05067,uniprotkb:O95864,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:A8K2M6|uniprotkb:Q6MZQ7|uniprotkb:Q9...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,psi-mi:fads2_human(display_short)|psi-mi:Acyl-...,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Hosp F. et al.(2015),intact:EBI-21132292|pubmed:25959826|imex:IM-27137,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0486""(UniProt)",intact:EBI-21132574|imex:IM-27137-1,-,P05067,P05067,ENSG00000142192
1,uniprotkb:P05067,uniprotkb:P13861,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:Q16823|intact:EBI-6116682|uniprotkb:...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,psi-mi:kap2_human(display_short)|psi-mi:cAMP-d...,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Hosp F. et al.(2015),intact:EBI-21132292|pubmed:25959826|imex:IM-27137,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0486""(UniProt)",intact:EBI-21132574|imex:IM-27137-1,-,P05067,P05067,ENSG00000142192
2,uniprotkb:P05067,uniprotkb:Q8TD31,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:Q9NRK8|uniprotkb:Q9NWY9|uniprotkb:Q9...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,psi-mi:cchcr_human(display_short)|psi-mi:Coile...,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Hosp F. et al.(2015),intact:EBI-21132292|pubmed:25959826|imex:IM-27137,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0486""(UniProt)",intact:EBI-21132574|imex:IM-27137-1,-,P05067,P05067,ENSG00000142192
3,uniprotkb:P05067,uniprotkb:Q15392,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:D3DQ51|uniprotkb:Q9HBA8|uniprotkb:B7...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,"psi-mi:dhc24_human(display_short)|psi-mi:""Delt...","psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Hosp F. et al.(2015),intact:EBI-21132292|pubmed:25959826|imex:IM-27137,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0486""(UniProt)",intact:EBI-21132574|imex:IM-27137-1,-,P05067,P05067,ENSG00000142192
4,uniprotkb:P05067,uniprotkb:Q15125,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:Q6IBI9|uniprotkb:Q6FGL3|ensembl:ENSP...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,"psi-mi:ebp_human(display_short)|psi-mi:""3-beta...","psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Hosp F. et al.(2015),intact:EBI-21132292|pubmed:25959826|imex:IM-27137,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0486""(UniProt)",intact:EBI-21132574|imex:IM-27137-1,-,P05067,P05067,ENSG00000142192

In [192]:
second_third_level_dataset = gene_dataset_with_ens[gene_dataset_with_ens['converted_alias'].isin(first_second_level_matched_ens_list)]

In [195]:
len(second_third_level_dataset['converted_alias'].unique().tolist())

133

In [196]:
len(second_third_level_dataset['ID(s) interactor B'].unique().tolist())

1274

In [197]:
adj_matrix_second_third = pd.crosstab(second_third_level_dataset['converted_alias'],second_third_level_dataset['ID(s) interactor B'])

In [206]:
adj_matrix_second_third.head()

ID(s) interactor B,intact:EBI-11820565,intact:EBI-20723938,intact:EBI-26519605,uniprotkb:A0A024R0E2,uniprotkb:A0A024R0H7,uniprotkb:A0A024R0M6,uniprotkb:A0A024R1K7,uniprotkb:A0A024R1U0,uniprotkb:A0A024R1U4,uniprotkb:A0A024R1Z6,...,uniprotkb:Q9Y6Y0,uniprotkb:R9S3C3,uniprotkb:V5YQL4,uniprotkb:V9HW22,uniprotkb:V9HW31,uniprotkb:V9HW96,uniprotkb:V9HWB4,uniprotkb:V9HWB8,uniprotkb:V9HWC2,uniprotkb:V9HWH9
converted_alias,,,,,,,,,,,,,,,,,,,,,
ENSG00000002822,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000003393,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000005884,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000007047,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000010278,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [213]:
len(set(adj_matrix_first_second.columns.tolist()).intersection(adj_matrix_second_third.index.tolist()))

133

In [215]:
adj_matrix_first_second.head()

gene_id,ENSG00000002822,ENSG00000003393,ENSG00000005884,ENSG00000007047,ENSG00000010278,ENSG00000010810,ENSG00000023191,ENSG00000034693,ENSG00000047457,ENSG00000051128,...,ENSG00000197122,ENSG00000197386,ENSG00000198087,ENSG00000198736,ENSG00000205155,ENSG00000205571,ENSG00000214253,ENSG00000221823,ENSG00000221829,ENSG00000227544
SNP_id,,,,,,,,,,,,,,,,,,,,,
10:102764091,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10:105221736,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10:112170486,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10:112558236,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10:112650209,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [216]:
adj_matrix_first_second.to_csv('adj_matrix_first_second.csv')

In [222]:
pd.read_csv('adj_matrix_first_second.csv',index_col = 'SNP_id').T

SNP_id,10:102764091,10:105221736,10:112170486,10:112558236,10:112650209,10:112802423,10:113118382,10:113125652,10:113489179,10:118984464,...,9:27558437,9:27573897,9:27578935,9:27583817,9:27586451,9:27594491,9:28387593,9:35022891,9:72014104,9:72128165
ENSG00000002822,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000003393,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000005884,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000007047,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000010278,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000205571,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000214253,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000221823,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000221829,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
ENSG00000227544,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [219]:
adj_matrix_second_third = adj_matrix_second_third.loc[adj_matrix_first_second.columns.tolist()]

In [220]:
adj_matrix_second_third.to_csv('adj_matrix_second_third.csv')

In [225]:
pd.read_csv('adj_matrix_second_third.csv',index_col = 'converted_alias').T

converted_alias,ENSG00000002822,ENSG00000003393,ENSG00000005884,ENSG00000007047,ENSG00000010278,ENSG00000010810,ENSG00000023191,ENSG00000034693,ENSG00000047457,ENSG00000051128,...,ENSG00000197122,ENSG00000197386,ENSG00000198087,ENSG00000198736,ENSG00000205155,ENSG00000205571,ENSG00000214253,ENSG00000221823,ENSG00000221829,ENSG00000227544
intact:EBI-11820565,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
intact:EBI-20723938,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
intact:EBI-26519605,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
uniprotkb:A0A024R0E2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
uniprotkb:A0A024R0H7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
uniprotkb:V9HW96,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
uniprotkb:V9HWB4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
uniprotkb:V9HWB8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
uniprotkb:V9HWC2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
uniprotkb:V9HWH9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Creating the dataset for Pytorch

In [65]:
df_list = [pd.read_csv(file,sep=' ',index_col='FID',usecols=lambda x: x not in ['PHENOTYPE','SEX','IID','PAT','MAT']) for file in csv_flies]

In [66]:
big_df = pd.concat(df_list,axis=1)

In [67]:
big_df.shape

(36620, 37606)

In [68]:
big_df.index

Int64Index([1767364, 2268235, 4521147, 5278224, 1925234, 5738107, 2218042,
            2405794, 4423490, 5773801,
            ...
            1202774, 1126932, 2754094, 3545763, 6000176, 4283752, 4622763,
            2870611, 5854257, 1107612],
           dtype='int64', name='FID', length=36620)

In [74]:
rs_ids = list(map(lambda x: x.split('_')[0],big_df.columns.tolist()))

In [75]:
big_df.columns = rs_ids

In [144]:
first_matched_rsids = first_second_level_genes.rs_id.unique().tolist()

In [145]:
len(first_matched_rsids)

400

In [146]:
selected_snps_dataset = big_df[first_matched_rsids]

In [147]:
selected_snps_dataset = selected_snps_dataset.loc[:,~selected_snps_dataset.columns.duplicated()]

#### Matching subjects with working memory data

In [91]:
label_file= '/data/users2/pnadigapusuresh1/Projects/ukbiobank/Data/subset_vars.csv'

In [92]:
vars = pd.read_csv(label_file,index_col='eid',
                            usecols=['eid','maximum_digits_remembered_correctly_f4282_2_0',
                            'sex_f31_0_0','age_when_attended_assessment_centre_f21003_0_0'])

In [93]:
vars.columns = ['sex','score','age']

In [94]:
vars

         sex  score   age
eid
5230587  1.0    8.0  57.0
2369031  0.0    7.0  45.0
4304744  0.0    7.0  69.0
4373404  1.0    6.0  51.0
1229224  1.0    8.0  60.0
...      ...    ...   ...
3001470  0.0    4.0  46.0
2677873  1.0    NaN  62.0
5343321  0.0    6.0  56.0
2504488  1.0    9.0  50.0
4348663  1.0    7.0  64.0

[39760 rows x 3 columns]

In [95]:
vars = vars.loc[vars.score.isin([2,3,4,5,9,10,11,12])]

In [105]:
selected_snps_dataset

,rs76332820,rs4944873,rs7131683,rs139848901,rs10793118,rs145191148,rs672701,rs12113715,rs186098536,rs6962921,...,rs12981911,rs8102125,rs11881662,rs75332038,rs310434,rs77980659,rs4447797,rs13062950,rs9839511,rs145914525
FID,,,,,,,,,,,,,,,,,,,,,
1767364,0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2268235,0,1.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0
4521147,0,1.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
5278224,0,1.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,...,2.0,1.0,0.0,0.0,0.0,0.0,1.0,2.0,1.0,0.0
1925234,0,2.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4283752,1,0.0,0.0,0.0,2.0,0.0,1.0,1.0,0.0,1.0,...,1.0,1.0,0.0,0.0,1.0,0.0,2.0,2.0,0.0,0.0
4622763,0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,2.0,1.0,0.0
2870611,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,0.0,NaN,NaN,0.0,1.0,1.0,1.0,0.0
5854257,0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,2.0,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1107612,1,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0

In [117]:
subjects_with_working_mem_and_gene = set(vars.index.tolist()).intersection(selected_snps_dataset.index.tolist())

In [119]:
gene_working_mem = selected_snps_dataset.loc[list(subjects_with_working_mem_and_gene)]

In [120]:
gene_working_mem

,rs76332820,rs4944873,rs7131683,rs139848901,rs10793118,rs145191148,rs672701,rs12113715,rs186098536,rs6962921,...,rs12981911,rs8102125,rs11881662,rs75332038,rs310434,rs77980659,rs4447797,rs13062950,rs9839511,rs145914525
FID,,,,,,,,,,,,,,,,,,,,,
2588677,0,0.0,1.0,0.0,2.0,0.0,2.0,1.0,0.0,2.0,...,2.0,1.0,0.0,0.0,1.0,1.0,0.0,2.0,0.0,0.0
3670029,0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,2.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0
1245201,1,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,2.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
2162713,0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,2.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5636125,0,2.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4259788,0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,2.0,0.0,0.0
5275598,0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3243989,0,0.0,0.0,0.0,NaN,0.0,0.0,2.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
1343446,0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,1.0,1.0,0.0,0.0,1.0,0.0,1.0,2.0,0.0,1.0
1671167,0,1.0,0.0,0.0,1.0,0.0,0.0,NaN,0.0,0.0,...,0.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

In [121]:
gene_working_mem.to_csv('gene_working_mem_dataset.csv')

In [136]:
gene_working_mem = gene_working_mem.fillna(0)

In [137]:
gene_working_mem

,rs76332820,rs4944873,rs7131683,rs139848901,rs10793118,rs145191148,rs672701,rs12113715,rs186098536,rs6962921,...,rs12981911,rs8102125,rs11881662,rs75332038,rs310434,rs77980659,rs4447797,rs13062950,rs9839511,rs145914525
FID,,,,,,,,,,,,,,,,,,,,,
2588677,0,0.0,1.0,0.0,2.0,0.0,2.0,1.0,0.0,2.0,...,2.0,1.0,0.0,0.0,1.0,1.0,0.0,2.0,0.0,0.0
3670029,0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,2.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0
1245201,1,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,2.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
2162713,0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,2.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5636125,0,2.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4259788,0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,2.0,0.0,0.0
5275598,0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3243989,0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
1343446,0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,1.0,1.0,0.0,0.0,1.0,0.0,1.0,2.0,0.0,1.0
1671167,0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

In [124]:
pd.read_csv('gene_working_mem_dataset.csv',index_col='FID')

,rs76332820,rs4944873,rs7131683,rs139848901,rs10793118,rs145191148,rs672701,rs12113715,rs186098536,rs6962921,...,rs12981911,rs8102125,rs11881662,rs75332038,rs310434,rs77980659,rs4447797,rs13062950,rs9839511,rs145914525
FID,,,,,,,,,,,,,,,,,,,,,
2588677,0,0.0,1.0,0.0,2.0,0.0,2.0,1.0,0.0,2.0,...,2.0,1.0,0.0,0.0,1.0,1.0,0.0,2.0,0.0,0.0
3670029,0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,2.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0
1245201,1,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,2.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
2162713,0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,2.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5636125,0,2.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4259788,0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,2.0,0.0,0.0
5275598,0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3243989,0,0.0,0.0,0.0,NaN,0.0,0.0,2.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
1343446,0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,1.0,1.0,0.0,0.0,1.0,0.0,1.0,2.0,0.0,1.0
1671167,0,1.0,0.0,0.0,1.0,0.0,0.0,NaN,0.0,0.0,...,0.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

In [132]:
vars = vars.loc[gene_working_mem.index.tolist()]

In [133]:
vars.iloc[200]

sex       0.0
score     4.0
age      53.0
Name: 4228319, dtype: float64

In [138]:
gene_working_mem.iloc[200].to_numpy()

array([0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 2., 1., 1., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 2., 2., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1.,
       0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 2., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 2., 0., 0., 1.,
       1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 2.,
       0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 1., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 2., 0., 0., 1., 0., 1.,
       0., 1., 0., 0., 1., 0., 2., 0., 0., 0., 1., 1., 0., 0., 0., 2., 0.,
       0., 0., 1., 0., 2., 0., 2., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 2., 1., 1., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 1., 1., 2., 0., 0., 0., 2., 0., 0., 1., 1., 0., 0., 0.,
       1., 0., 1., 2., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1.,
       0., 1., 0., 0., 2., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       1., 1., 0., 2., 0., 0., 0., 0., 0., 1., 1., 0., 0., 2., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 2., 0., 2., 1.,
       1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       1., 0., 0., 2., 2., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1.,
       0., 0., 0., 1., 2., 0., 0., 0., 0., 0., 2., 0., 0., 0., 1., 2., 0.,
       1., 0., 0., 1., 0., 0., 0., 0., 0.])

In [139]:
import torch

In [140]:
torch.tensor(gene_working_mem.iloc[200].to_numpy())

tensor([0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 2., 1., 1., 0., 0.,
        0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 2., 2., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1.,
        0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
        0., 1., 0., 0., 0., 2., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 2., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
        0., 1., 0., 1., 0., 0., 0., 0., 2., 0., 0., 2., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 2., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        1., 2., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 2., 0., 0., 0., 1.,
        1., 0., 0., 0., 2., 0., 0., 0., 1., 0., 2., 0., 2., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 2., 1., 1., 0., 0., 1.,
        0., 0., 0., 1., 0., 0., 0., 1., 1., 2., 0., 0., 0., 2., 0., 0., 1., 1.,
        0., 0., 0., 1., 0., 1., 2., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0.,
        0., 1., 0., 1., 0., 0., 2., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
        1., 1., 0., 2., 0., 0., 0., 0., 0., 1., 1., 0., 0., 2., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 2., 0., 2., 1., 1., 1.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0.,
        2., 2., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1.,
        2., 0., 0., 0., 0., 0., 2., 0., 0., 0., 1., 2., 0., 1., 0., 0., 1., 0.,
        0., 0., 0., 0.], dtype=torch.float64)