In [1]:
import pandas as pd
import numpy as np
import glob

In [2]:
eQTL = pd.read_csv('/data/users2/pnadigapusuresh1/Projects/ukbiobank/Data/QTL/eQTL_hg19_1FPKM_with_rs_id.csv')
eQTL
eQTL.head()

,Unnamed: 0,gene_id,gene_chr,gene_start,gene_end,strand,number_of_SNPs_tested,SNP_distance_to_TSS,SNP_id,SNP_chr,SNP_start,SNP_end,nominal_pval,regression_slope,top_SNP,FDR,snps,rs_id
0,0,ENSG00000204316,chr17,73901494,73901494,+,3394,-955836,17:72945658,chr17,72945658,72945658,0.000852,0.057756,0,0.029260,72945658,rs77018335
1,1,ENSG00000204316,chr17,73901494,73901494,+,3394,-546694,17:73354800,chr17,73354800,73354800,0.001217,-0.099736,0,0.039173,73354800,rs1237746321
2,2,ENSG00000204316,chr17,73901494,73901494,+,3394,-118750,17:73782744,chr17,73782744,73782744,0.000407,-0.097620,0,0.015733,73782744,rs8077281
3,3,ENSG00000204316,chr17,73901494,73901494,+,3394,-59792,17:73841702,chr17,73841702,73841702,0.001396,-0.041055,0,0.043746,73841702,rs9900122
4,4,ENSG00000204316,chr17,73901494,73901494,+,3394,-54978,17:73846516,chr17,73846516,73846516,0.000189,-0.053441,0,0.008126,73846516,rs2004452

#### snps selected after LD pruning using 0.4 treshold

In [3]:
pruned_snps = glob.glob('/data/users2/pnadigapusuresh1/Projects/ukbiobank/Data/QTL/*.in')

In [4]:
pruned_snps[-1]

'/data/users2/pnadigapusuresh1/Projects/ukbiobank/Data/QTL/filtered_chr4_pruned.prune.in'

In [5]:
snps_pruned_in = [pd.read_csv(file,header=None) for file in pruned_snps]

In [6]:
snps_pruned_in[-1]

                0
0      rs74376569
1       rs4690234
2      rs77664329
3      rs73213593
4     rs184624056
...           ...
4536   rs11132422
4537    rs7438638
4538    rs2685871
4539   rs78412373
4540    rs1915852

[4541 rows x 1 columns]

In [7]:
all_snps_pruned_in = pd.concat(snps_pruned_in,axis=0)

In [8]:
all_snps_pruned_in

               0
0     rs61149995
1     rs13437666
2     rs79146206
3     rs12669154
4      rs6975321
...          ...
4536  rs11132422
4537   rs7438638
4538   rs2685871
4539  rs78412373
4540   rs1915852

[90303 rows x 1 columns]

In [9]:
eQTL = eQTL[eQTL['rs_id'].isin(all_snps_pruned_in[0])]

In [10]:
eQTL

,Unnamed: 0,gene_id,gene_chr,gene_start,gene_end,strand,number_of_SNPs_tested,SNP_distance_to_TSS,SNP_id,SNP_chr,SNP_start,SNP_end,nominal_pval,regression_slope,top_SNP,FDR,snps,rs_id
30,30,ENSG00000204316,chr17,73901494,73901494,+,3394,-806,17:73900688,chr17,73900688,73900688,3.710300e-05,-0.052116,1,0.001932,73900688,rs3744015
33,33,ENSG00000204316,chr17,73901494,73901494,+,3394,40702,17:73942196,chr17,73942196,73942196,3.908310e-05,0.131688,0,0.002024,73942196,rs71382188
40,40,ENSG00000204316,chr17,73901494,73901494,+,3394,984744,17:74886238,chr17,74886238,74886238,1.270460e-03,-0.044652,0,0.040553,74886238,rs554012
41,41,ENSG00000188878,chr17,73937119,73937119,+,3477,-776304,17:73160815,chr17,73160815,73160815,4.038930e-05,0.346087,0,0.002084,73160815,rs138046159
47,47,ENSG00000257949,chr17,73975301,73975301,+,3544,-923391,17:73051910,chr17,73051910,73051910,1.357750e-03,0.059355,0,0.042780,73051910,rs8065776
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2120702,2120702,ENSG00000186532,chr17,1733175,1733175,+,4191,-774661,17:958514,chr17,958514,958514,5.168770e-04,-0.115433,0,0.019258,958514,rs2261299
2120706,2120706,ENSG00000186532,chr17,1733175,1733175,+,4191,-67469,17:1665706,chr17,1665706,1665706,2.466890e-05,0.088098,0,0.001340,1665706,rs62088170
2120707,2120707,ENSG00000186532,chr17,1733175,1733175,+,4191,-66922,17:1666253,chr17,1666253,1666253,2.396940e-07,0.118849,0,0.000019,1666253,rs62088172
2120727,2120727,ENSG00000186532,chr17,1733175,1733175,+,4191,2294,17:1735469,chr17,1735469,1735469,1.770990e-04,0.087676,0,0.007680,1735469,rs56157802
2120750,2120750,ENSG00000185924,chr17,1928639,1928639,+,4336,-16641,17:1911998,chr17,1911998,1911998,1.324730e-03,0.032620,1,0.041942,1911998,rs72809519

In [11]:
snps = eQTL.SNP_id

### Saving the eQTL with their rs_id

In [ ]:
eQTL.to_csv('./eQTL_hg19_1FPKM_with_rs_id.csv')

In [18]:
snps.to_csv('rs_snps_eqtl.txt',index=True)

In [36]:
snps = pd.read_csv('./rs_snps_eqtl.txt')

In [8]:
final_snps = pd.read_csv('../ukb_cal_imggen_eQTL_matched_recode.raw',delim_whitespace=True,nrows=3)

In [9]:
final_snps.shape

(3, 28654)

In [10]:
final_snps.columns

Index(['FID', 'IID', 'PAT', 'MAT', 'SEX', 'PHENOTYPE', 'rs3128109_T',
       'rs4970349_C', 'rs2799072_C', 'rs11260596_T',
       ...
       'rs6151416_A', 'rs5770964_G', 'rs117063829_T', 'rs6010045_T',
       'rs36006314_G', 'rs2157711_C', 'rs5770821_G', 'rs78342408_T',
       'rs56207913_T', 'rs73174437_T'],
      dtype='object', length=28654)

In [2]:
for i in range(1,23):
    print(f'ukb_imputed_imggen_chr{i}')

ukb_imputed_imggen_chr1
ukb_imputed_imggen_chr2
ukb_imputed_imggen_chr3
ukb_imputed_imggen_chr4
ukb_imputed_imggen_chr5
ukb_imputed_imggen_chr6
ukb_imputed_imggen_chr7
ukb_imputed_imggen_chr8
ukb_imputed_imggen_chr9
ukb_imputed_imggen_chr10
ukb_imputed_imggen_chr11
ukb_imputed_imggen_chr12
ukb_imputed_imggen_chr13
ukb_imputed_imggen_chr14
ukb_imputed_imggen_chr15
ukb_imputed_imggen_chr16
ukb_imputed_imggen_chr17
ukb_imputed_imggen_chr18
ukb_imputed_imggen_chr19
ukb_imputed_imggen_chr20
ukb_imputed_imggen_chr21
ukb_imputed_imggen_chr22

## Creating the ADJ matrices

In [3]:
csv_flies = glob.glob('/data/users2/pnadigapusuresh1/Projects/ukbiobank/Data/QTL'+'/*pruned_recoded.raw')

In [4]:
df_list = [pd.read_csv(file,sep=' ',nrows=3,index_col='FID',usecols=lambda x: x not in ['PHENOTYPE','SEX','IID','PAT','MAT']) for file in csv_flies]

In [5]:
df_list[20].iloc[:,:10]

,rs6975321_A,rs11981721_C,rs4593475_C,rs6968087_A,rs28378990_A,rs6461090_G,rs56335616_G,rs11768769_G,rs4722379_A,rs61296767_G
FID,,,,,,,,,,
1767364,0,NaN,2,0,0,1,0,0,0,0
2268235,1,1.0,2,1,1,0,0,0,0,1
4521147,0,0.0,0,0,0,1,0,0,0,0

In [6]:
big_df = pd.concat(df_list,axis=1)

In [7]:
big_df.shape

(3, 19387)

In [8]:
big_df.iloc[:,:10]

,rs34726335_A,rs36020100_A,rs6598823_C,rs149570429_G,rs34623718_A,rs1570000_C,rs62067253_T,rs9898238_C,rs12451243_T,rs73289698_A
FID,,,,,,,,,,
1767364,0,2,1,0,0,0,NaN,1,0,1
2268235,1,1,0,1,0,0,0.0,2,0,0
4521147,1,0,0,0,0,0,0.0,2,0,0

In [9]:
final_snps = big_df.columns.tolist()
final_snps = list(map(lambda snp: snp.split('_')[0],final_snps))
final_eqtls = eQTL[eQTL['rs_id'].isin(final_snps)]

In [10]:
len(final_eqtls['gene_id'].unique())

9030

In [11]:
len(final_eqtls['SNP_id'].unique())

19369

In [12]:
final_eqtls.groupby(['SNP_id','gene_id']).size()

SNP_id        gene_id
10:100126295  ENSG00000119943    1
10:100189928  ENSG00000107521    1
10:100240011  ENSG00000107521    1
10:101108742  ENSG00000172987    1
10:101187316  ENSG00000172987    1
                                ..
9:99983931    ENSG00000188801    1
              ENSG00000203279    1
              ENSG00000213612    1
              ENSG00000228038    1
              ENSG00000255036    1
Length: 29345, dtype: int64

In [13]:
final_eqtls[final_eqtls.duplicated(['SNP_id'])]

,Unnamed: 0,gene_id,gene_chr,gene_start,gene_end,strand,number_of_SNPs_tested,SNP_distance_to_TSS,SNP_id,SNP_chr,SNP_start,SNP_end,nominal_pval,regression_slope,top_SNP,FDR,snps,rs_id
406,406,ENSG00000141576,chr17,74236454,74236454,+,3782,-52937,17:74183517,chr17,74183517,74183517,7.829400e-04,-0.033850,0,2.727275e-02,74183517,rs8074651
524,524,ENSG00000129646,chr17,74303761,74303761,+,3881,-348986,17:73954775,chr17,73954775,73954775,6.145050e-04,0.095243,0,2.227802e-02,73954775,rs8064857
731,731,ENSG00000161542,chr17,74350230,74350230,+,3934,-180548,17:74169682,chr17,74169682,74169682,6.630810e-05,0.161026,0,3.242118e-03,74169682,rs11655525
839,839,ENSG00000161542,chr17,74350230,74350230,+,3934,-68160,17:74282070,chr17,74282070,74282070,3.124270e-04,0.175619,0,1.254436e-02,74282070,rs36029382
926,926,ENSG00000161542,chr17,74350230,74350230,+,3934,-28235,17:74321995,chr17,74321995,74321995,1.266110e-25,0.232420,0,5.130876e-23,74321995,rs10468437
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2119740,2119740,ENSG00000167695,chr17,635652,635652,+,2779,55871,17:691523,chr17,691523,691523,4.006200e-09,0.183378,0,4.174876e-07,691523,rs1570000
2120045,2120045,ENSG00000167193,chr17,1359517,1359517,+,4172,-138614,17:1220903,chr17,1220903,1220903,7.875110e-04,0.092571,0,2.740477e-02,1220903,rs35027121
2120114,2120114,ENSG00000167193,chr17,1359517,1359517,+,4172,-104416,17:1255101,chr17,1255101,1255101,3.055100e-04,-0.096901,0,1.230454e-02,1255101,rs62087918
2120442,2120442,ENSG00000074660,chr17,1549041,1549041,+,4332,746973,17:2296014,chr17,2296014,2296014,5.274290e-05,0.060367,0,2.645992e-03,2296014,rs2447091
2120443,2120443,ENSG00000074660,chr17,1549041,1549041,+,4332,754346,17:2303387,chr17,2303387,2303387,9.281800e-07,0.147585,0,6.732182e-05,2303387,rs12602313

#### Loading Alzhiemers protien ID's

In [14]:
p_g = pd.read_csv('/data/users2/pnadigapusuresh1/Projects/ukbiobank/bio_informed_nn/gProfiler_hsapiens_6-20-2023_4-00-56 PM.csv')

In [15]:
p_g.columns

Index(['initial_alias', 'converted_alias', 'name', 'description', 'namespace'], dtype='object')

In [16]:
p_g_new = p_g.drop_duplicates(subset=['initial_alias','converted_alias'])

In [17]:
p_g_new

,initial_alias,converted_alias,name,description,namespace
0,P05067,ENSG00000142192,APP,amyloid beta precursor protein [Source:HGNC Sy...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
30,P49768,ENSG00000080815,PSEN1,presenilin 1 [Source:HGNC Symbol;Acc:HGNC:9508],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
104,P54253,ENSG00000124788,ATXN1,ataxin 1 [Source:HGNC Symbol;Acc:HGNC:10548],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
151,P42858,ENSG00000197386,HTT,huntingtin [Source:HGNC Symbol;Acc:HGNC:4851],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
270,O14672,ENSG00000137845,ADAM10,ADAM metallopeptidase domain 10 [Source:HGNC S...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
...,...,...,...,...,...
3237,P43116,ENSG00000125384,PTGER2,prostaglandin E receptor 2 [Source:HGNC Symbol...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
3245,P53805,ENSG00000159200,RCAN1,regulator of calcineurin 1 [Source:HGNC Symbol...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
3264,Q96L34,ENSG00000007047,MARK4,microtubule affinity regulating kinase 4 [Sour...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
3269,Q7KZI7,ENSG00000072518,MARK2,microtubule affinity regulating kinase 2 [Sour...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
3271,Q9P0L2,ENSG00000116141,MARK1,microtubule affinity regulating kinase 1 [Sour...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"

In [18]:
len(p_g_new['converted_alias'].unique())

214

In [19]:
alzhimers_gene_id = p_g_new['converted_alias'].unique().tolist()

#### Matching final_eqtl gene_id with the alzhiemer's gene id

In [20]:
first_second_level_genes = final_eqtls[final_eqtls['gene_id'].isin(alzhimers_gene_id)]

In [21]:
first_second_level_genes

,Unnamed: 0,gene_id,gene_chr,gene_start,gene_end,strand,number_of_SNPs_tested,SNP_distance_to_TSS,SNP_id,SNP_chr,SNP_start,SNP_end,nominal_pval,regression_slope,top_SNP,FDR,snps,rs_id
19166,19166,ENSG00000175582,chr11,73472182,73472182,+,3320,-16890,11:73455292,chr11,73455292,73455292,4.280480e-08,-0.086313,0,0.000004,73455292,rs10898940
19308,19308,ENSG00000175582,chr11,73472182,73472182,+,3320,233082,11:73705264,chr11,73705264,73705264,7.062160e-05,0.061784,0,0.003427,73705264,rs4944873
22000,22000,ENSG00000149243,chr11,75141236,75141236,+,3064,-14506,11:75126730,chr11,75126730,75126730,2.960680e-04,0.054877,0,0.011975,75126730,rs10793118
64634,64634,ENSG00000214253,chr7,100888356,100888356,+,3963,387403,7:101275759,chr7,101275759,101275759,1.020610e-03,0.041162,0,0.033945,101275759,rs6965171
90300,90300,ENSG00000158161,chr1,28415207,28415207,+,2577,-104562,1:28310645,chr1,28310645,28310645,5.119040e-04,0.144251,0,0.019101,28310645,rs141365059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2100537,2100537,ENSG00000108107,chr19,55896713,55896713,+,3286,4156,19:55900869,chr19,55900869,55900869,4.528700e-04,-0.033258,0,0.017221,55900869,rs12981911
2100546,2100546,ENSG00000108107,chr19,55896713,55896713,+,3286,13519,19:55910232,chr19,55910232,55910232,8.307520e-08,-0.071469,0,0.000007,55910232,rs11673539
2111777,2111777,ENSG00000175166,chr3,184016497,184016497,+,4337,-842498,3:183173999,chr3,183173999,183173999,1.631780e-03,0.037988,0,0.049569,183173999,rs6794101
2111782,2111782,ENSG00000175166,chr3,184016497,184016497,+,4337,-77640,3:183938857,chr3,183938857,183938857,9.480040e-04,-0.038527,0,0.031945,183938857,rs4447797
2111786,2111786,ENSG00000175166,chr3,184016497,184016497,+,4337,14341,3:184030838,chr3,184030838,184030838,2.077060e-04,-0.054728,0,0.008820,184030838,rs34390533

In [22]:
second_level_matched_genes = first_second_level_genes['gene_id'].unique().tolist()

In [23]:
len(second_level_matched_genes)

88

##### First level SNPs and 2nd level Genes

In [24]:
len(first_second_level_genes['SNP_id'].unique().tolist())

271

In [25]:
first_second_level_genes[first_second_level_genes['SNP_id'].duplicated()]

,Unnamed: 0,gene_id,gene_chr,gene_start,gene_end,strand,number_of_SNPs_tested,SNP_distance_to_TSS,SNP_id,SNP_chr,SNP_start,SNP_end,nominal_pval,regression_slope,top_SNP,FDR,snps,rs_id
205458,205458,ENSG00000125826,chr20,388142,388142,+,2901,-22309,20:365833,chr20,365833,365833,8.968220e-06,0.075987,0,5.367665e-04,365833,rs6107242
1537144,1537144,ENSG00000177697,chr11,832843,832843,+,3978,-131120,11:701723,chr11,701723,701723,4.548900e-05,0.065537,0,2.318418e-03,701723,rs10902200
1537290,1537290,ENSG00000177697,chr11,832843,832843,+,3978,209124,11:1041967,chr11,1041967,1041967,1.728190e-05,-0.071387,0,9.720583e-04,1041967,rs72842424
1932543,1932543,ENSG00000188906,chr12,40590546,40590546,+,4037,-416384,12:40174162,chr12,40174162,40174162,2.575480e-08,-0.068498,0,2.402385e-06,40174162,rs12424789
1932866,1932866,ENSG00000188906,chr12,40590546,40590546,+,4037,627,12:40591173,chr12,40591173,40591173,9.227820e-20,0.102930,0,2.598355e-17,40591173,rs1491922

In [26]:
adj_matrix_first_second = pd.crosstab(first_second_level_genes['SNP_id'],first_second_level_genes['gene_id'])

In [27]:
adj_matrix_first_second.shape

(271, 88)

In [29]:
with open('first_second_adj_matrix.npy','wb') as f:
    np.save(f, adj_matrix_first_second.to_numpy())

#### Mstching these matched genes between eqtl's and alzhiemers genes for third level connections

In [30]:
gene_dataset = pd.read_csv('2023-06-16-10-44.txt',delimiter='\t')

In [31]:
gene_dataset

,# ID(s) interactor A,ID(s) interactor B,Alt. ID(s) interactor A,Alt. ID(s) interactor B,Alias(es) interactor A,Alias(es) interactor B,Interaction detection method(s),Publication 1st author(s),Publication Identifier(s),Taxid interactor A,Taxid interactor B,Interaction type(s),Source database(s),Interaction identifier(s),Confidence value(s)
0,uniprotkb:P05067,uniprotkb:O95864,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:A8K2M6|uniprotkb:Q6MZQ7|uniprotkb:Q9...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,psi-mi:fads2_human(display_short)|psi-mi:Acyl-...,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Hosp F. et al.(2015),intact:EBI-21132292|pubmed:25959826|imex:IM-27137,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0486""(UniProt)",intact:EBI-21132574|imex:IM-27137-1,-
1,uniprotkb:P05067,uniprotkb:P13861,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:Q16823|intact:EBI-6116682|uniprotkb:...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,psi-mi:kap2_human(display_short)|psi-mi:cAMP-d...,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Hosp F. et al.(2015),intact:EBI-21132292|pubmed:25959826|imex:IM-27137,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0486""(UniProt)",intact:EBI-21132574|imex:IM-27137-1,-
2,uniprotkb:P05067,uniprotkb:Q8TD31,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:Q9NRK8|uniprotkb:Q9NWY9|uniprotkb:Q9...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,psi-mi:cchcr_human(display_short)|psi-mi:Coile...,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Hosp F. et al.(2015),intact:EBI-21132292|pubmed:25959826|imex:IM-27137,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0486""(UniProt)",intact:EBI-21132574|imex:IM-27137-1,-
3,uniprotkb:P05067,uniprotkb:Q15392,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:D3DQ51|uniprotkb:Q9HBA8|uniprotkb:B7...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,"psi-mi:dhc24_human(display_short)|psi-mi:""Delt...","psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Hosp F. et al.(2015),intact:EBI-21132292|pubmed:25959826|imex:IM-27137,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0486""(UniProt)",intact:EBI-21132574|imex:IM-27137-1,-
4,uniprotkb:P05067,uniprotkb:Q15125,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:Q6IBI9|uniprotkb:Q6FGL3|ensembl:ENSP...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,"psi-mi:ebp_human(display_short)|psi-mi:""3-beta...","psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Hosp F. et al.(2015),intact:EBI-21132292|pubmed:25959826|imex:IM-27137,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0486""(UniProt)",intact:EBI-21132574|imex:IM-27137-1,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,uniprotkb:P05067,uniprotkb:P63104,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:P29213|uniprotkb:P29312|uniprotkb:Q3...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,psi-mi:1433z_human(display_short)|psi-mi:14-3-...,"psi-mi:""MI:0006""(anti bait coimmunoprecipitation)",Cottrell BA. et al.(2005),intact:EBI-1993060|pubmed:16049941|imex:IM-20090,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0469""(European Bioinformatics Insti...",intact:EBI-960318|imex:IM-20090-2,-
2396,uniprotkb:P05067,uniprotkb:P07900,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,intact:EBI-1642144|uniprotkb:Q2PP14|ensembl:EN...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,psi-mi:hs90a_human(display_short)|psi-mi:Heat ...,"psi-mi:""MI:0006""(anti bait coimmunoprecipitation)",Cottrell BA. et al.(2005),intact:EBI-1993060|pubmed:16049941|imex:IM-20090,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0469""(European Bioinformatics Insti...",intact:EBI-960318|imex:IM-20090-2,-
2397,uniprotkb:P05067,uniprotkb:P46459,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:Q8N6D7|uniprotkb:Q9UKZ2|uniprotkb:A8...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,psi-mi:nsf_human(display_short)|psi-mi:Vesicle...,"psi-mi:""MI:0006""(anti bait coimmunoprecipitation)",Cottrell BA. et al.(2005),intact:EBI-1993060|pubmed:16049941|imex:IM-20090,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0469""(European Bioinformatics Insti...",intact:EBI-960318|imex:IM-20090-2,-
2398,uniprotkb:P10636,uniprotkb:P27448,uniprotkb:P18518|uniprotkb:Q14799|uniprotkb:Q1...,uniprotkb:O60219|uniprotkb:Q8TB41|uniprotkb:Q8...,psi-mi:tau_human(display_short)|psi-mi:Microtu...,psi-mi:mark3_human(display_short)|psi-mi:MAP/m...,"psi-mi:""MI:0813""(proximity ligation assay)",Gu G.J. et al.(2013),intact:EBI-9699845|pubmed:23666762|imex:IM-23074,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:2364""(proximity)","psi-mi:""MI:0469""(European Bioinformatics Insti...",intact:EBI-9700143|imex:IM-23074-5,-
2399,uniprotkb:P05067,uniprotkb:Q05193,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:A6NLM6|uniprotkb:Q5SYX0|uniprotkb:Q5...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,psi-mi:dyn1_human(display_short)|psi-mi:Dynami...,"psi-mi:""MI:0006""(anti bait coimmunoprecipitation)",Cottrell BA. et al.(2005),intact:EBI-1993060|pubmed:16049941|imex:IM-20090,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0469""(European Bioinformatics Insti...",intact:EBI-960318|imex:IM-20090-2,-

In [32]:
gene_dataset['Interactor A P_id'] = list(map(lambda x: (x.split(':')[1]).split('-')[0], gene_dataset['# ID(s) interactor A'].tolist()))

In [33]:
first_second_level_matched_genes =  p_g_new[p_g_new['converted_alias'].isin(second_level_matched_genes)]

In [34]:
first_second_level_matched_genes

,initial_alias,converted_alias,name,description,namespace
0,P05067,ENSG00000142192,APP,amyloid beta precursor protein [Source:HGNC Sy...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
30,P49768,ENSG00000080815,PSEN1,presenilin 1 [Source:HGNC Symbol;Acc:HGNC:9508],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
104,P54253,ENSG00000124788,ATXN1,ataxin 1 [Source:HGNC Symbol;Acc:HGNC:10548],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
151,P42858,ENSG00000197386,HTT,huntingtin [Source:HGNC Symbol;Acc:HGNC:4851],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
270,O14672,ENSG00000137845,ADAM10,ADAM metallopeptidase domain 10 [Source:HGNC S...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
...,...,...,...,...,...
3225,P49407,ENSG00000137486,ARRB1,arrestin beta 1 [Source:HGNC Symbol;Acc:HGNC:711],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
3235,P32121,ENSG00000141480,ARRB2,arrestin beta 2 [Source:HGNC Symbol;Acc:HGNC:712],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
3245,P53805,ENSG00000159200,RCAN1,regulator of calcineurin 1 [Source:HGNC Symbol...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
3264,Q96L34,ENSG00000007047,MARK4,microtubule affinity regulating kinase 4 [Sour...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
3271,Q9P0L2,ENSG00000116141,MARK1,microtubule affinity regulating kinase 1 [Sour...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"

In [35]:
first_second_level_matched_genes_list = first_second_level_matched_genes['initial_alias'].unique().tolist()

In [36]:
first_second_level_matched_ens_list = first_second_level_matched_genes['converted_alias'].unique().tolist()

In [37]:
len(first_second_level_matched_genes['converted_alias'].unique().tolist())

149

In [38]:
len(first_second_level_matched_genes_list)

147

##### 2 genes of first_secong level matched genes (133) are missing in gene dataset

In [39]:
first_second_level_matched_genes.head()

,initial_alias,converted_alias,name,description,namespace
0,P05067,ENSG00000142192,APP,amyloid beta precursor protein [Source:HGNC Sy...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
30,P49768,ENSG00000080815,PSEN1,presenilin 1 [Source:HGNC Symbol;Acc:HGNC:9508],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
104,P54253,ENSG00000124788,ATXN1,ataxin 1 [Source:HGNC Symbol;Acc:HGNC:10548],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
151,P42858,ENSG00000197386,HTT,huntingtin [Source:HGNC Symbol;Acc:HGNC:4851],"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"
270,O14672,ENSG00000137845,ADAM10,ADAM metallopeptidase domain 10 [Source:HGNC S...,"UNIPROTSWISSPROT_ACC,UNIPROT_GN_ACC"

In [40]:
gene_dataset['initial_alias'] = gene_dataset['Interactor A P_id']

In [41]:
gene_dataset_with_ens = gene_dataset.join(first_second_level_matched_genes[['initial_alias','converted_alias']].set_index('initial_alias'),on='initial_alias')

In [42]:
gene_dataset_with_ens.head()

,# ID(s) interactor A,ID(s) interactor B,Alt. ID(s) interactor A,Alt. ID(s) interactor B,Alias(es) interactor A,Alias(es) interactor B,Interaction detection method(s),Publication 1st author(s),Publication Identifier(s),Taxid interactor A,Taxid interactor B,Interaction type(s),Source database(s),Interaction identifier(s),Confidence value(s),Interactor A P_id,initial_alias,converted_alias
0,uniprotkb:P05067,uniprotkb:O95864,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:A8K2M6|uniprotkb:Q6MZQ7|uniprotkb:Q9...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,psi-mi:fads2_human(display_short)|psi-mi:Acyl-...,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Hosp F. et al.(2015),intact:EBI-21132292|pubmed:25959826|imex:IM-27137,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0486""(UniProt)",intact:EBI-21132574|imex:IM-27137-1,-,P05067,P05067,ENSG00000142192
1,uniprotkb:P05067,uniprotkb:P13861,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:Q16823|intact:EBI-6116682|uniprotkb:...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,psi-mi:kap2_human(display_short)|psi-mi:cAMP-d...,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Hosp F. et al.(2015),intact:EBI-21132292|pubmed:25959826|imex:IM-27137,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0486""(UniProt)",intact:EBI-21132574|imex:IM-27137-1,-,P05067,P05067,ENSG00000142192
2,uniprotkb:P05067,uniprotkb:Q8TD31,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:Q9NRK8|uniprotkb:Q9NWY9|uniprotkb:Q9...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,psi-mi:cchcr_human(display_short)|psi-mi:Coile...,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Hosp F. et al.(2015),intact:EBI-21132292|pubmed:25959826|imex:IM-27137,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0486""(UniProt)",intact:EBI-21132574|imex:IM-27137-1,-,P05067,P05067,ENSG00000142192
3,uniprotkb:P05067,uniprotkb:Q15392,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:D3DQ51|uniprotkb:Q9HBA8|uniprotkb:B7...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,"psi-mi:dhc24_human(display_short)|psi-mi:""Delt...","psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Hosp F. et al.(2015),intact:EBI-21132292|pubmed:25959826|imex:IM-27137,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0486""(UniProt)",intact:EBI-21132574|imex:IM-27137-1,-,P05067,P05067,ENSG00000142192
4,uniprotkb:P05067,uniprotkb:Q15125,ensembl:ENSP00000284981.4|uniprotkb:P09000|uni...,uniprotkb:Q6IBI9|uniprotkb:Q6FGL3|ensembl:ENSP...,psi-mi:a4_human(display_short)|psi-mi:Amyloid-...,"psi-mi:ebp_human(display_short)|psi-mi:""3-beta...","psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Hosp F. et al.(2015),intact:EBI-21132292|pubmed:25959826|imex:IM-27137,taxid:9606(human)|taxid:9606(Homo sapiens),taxid:9606(human)|taxid:9606(Homo sapiens),"psi-mi:""MI:0914""(association)","psi-mi:""MI:0486""(UniProt)",intact:EBI-21132574|imex:IM-27137-1,-,P05067,P05067,ENSG00000142192

In [43]:
second_third_level_dataset = gene_dataset_with_ens[gene_dataset_with_ens['converted_alias'].isin(first_second_level_matched_ens_list)]

In [44]:
len(second_third_level_dataset['converted_alias'].unique().tolist())

149

In [45]:
len(second_third_level_dataset['ID(s) interactor B'].unique().tolist())

1283

In [46]:
adj_matrix_second_third = pd.crosstab(second_third_level_dataset['converted_alias'],second_third_level_dataset['ID(s) interactor B'])

In [47]:
adj_matrix_second_third.head()

ID(s) interactor B,intact:EBI-11820565,intact:EBI-20723938,intact:EBI-26519605,uniprotkb:A0A024R0E2,uniprotkb:A0A024R0H7,uniprotkb:A0A024R0M6,uniprotkb:A0A024R1K7,uniprotkb:A0A024R1U0,uniprotkb:A0A024R1U4,uniprotkb:A0A024R1Z6,...,uniprotkb:Q9Y6Y0,uniprotkb:R9S3C3,uniprotkb:V5YQL4,uniprotkb:V9HW22,uniprotkb:V9HW31,uniprotkb:V9HW96,uniprotkb:V9HWB4,uniprotkb:V9HWB8,uniprotkb:V9HWC2,uniprotkb:V9HWH9
converted_alias,,,,,,,,,,,,,,,,,,,,,
ENSG00000002822,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000003393,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000005884,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000007047,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000010278,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [48]:
len(set(adj_matrix_first_second.columns.tolist()).intersection(adj_matrix_second_third.index.tolist()))

149

In [49]:
adj_matrix_first_second.head()

gene_id,ENSG00000002822,ENSG00000003393,ENSG00000005884,ENSG00000007047,ENSG00000010278,ENSG00000010810,ENSG00000023191,ENSG00000034693,ENSG00000047457,ENSG00000051128,...,ENSG00000197122,ENSG00000197386,ENSG00000198087,ENSG00000198736,ENSG00000205155,ENSG00000205571,ENSG00000214253,ENSG00000221823,ENSG00000221829,ENSG00000227544
SNP_id,,,,,,,,,,,,,,,,,,,,,
10:102764091,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10:105056473,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10:105202501,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10:105221736,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10:105260534,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [50]:
adj_matrix_first_second.to_csv('adj_matrix_first_second.csv')

In [51]:
adj_matrix_first_second = pd.read_csv('adj_matrix_first_second.csv',index_col = 'SNP_id').T

In [52]:
adj_matrix_first_second.values.sum()

1070

In [54]:
adj_matrix_second_third.to_csv('adj_matrix_second_third.csv')

In [55]:
adj_matrix_second_third = pd.read_csv('adj_matrix_second_third.csv',index_col = 'converted_alias').T

## Creating the dataset for Pytorch

In [4]:
df_list = [pd.read_csv(file,sep=' ',nrows=3,index_col='FID',usecols=lambda x: x not in ['PHENOTYPE','SEX','IID','PAT','MAT']) for file in csv_flies]

In [ ]:
big_df = pd.concat(df_list,axis=1)

In [ ]:
big_df.shape

(36620, 90506)

In [ ]:
big_df.index

Int64Index([1767364, 2268235, 4521147, 5278224, 1925234, 5738107, 2218042,
            2405794, 4423490, 5773801,
            ...
            1202774, 1126932, 2754094, 3545763, 6000176, 4283752, 4622763,
            2870611, 5854257, 1107612],
           dtype='int64', name='FID', length=36620)

In [ ]:
rs_ids = list(map(lambda x: x.split('_')[0],big_df.columns.tolist()))

In [ ]:
big_df.columns = rs_ids

In [ ]:
first_matched_rsids = first_second_level_genes.rs_id.unique().tolist()

In [ ]:
len(first_matched_rsids)

1060

In [ ]:
selected_snps_dataset = big_df[first_matched_rsids]

In [ ]:
selected_snps_dataset

,rs11235827,rs10898940,rs67259239,rs1670546,rs76332820,rs72982970,rs4944873,rs146217454,rs41311857,rs72985970,...,rs75332038,rs310434,rs6794101,rs2662764,rs77980659,rs4447797,rs13062950,rs34390533,rs9839511,rs145914525
FID,,,,,,,,,,,,,,,,,,,,,
1767364,0.0,2.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2268235,1.0,2.0,0,0.0,0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0
4521147,0.0,2.0,0,0.0,0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
5278224,0.0,0.0,0,2.0,0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,2.0,1.0,1.0,0.0
1925234,2.0,0.0,1,2.0,0,1.0,2.0,NaN,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4283752,0.0,2.0,0,0.0,1,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,2.0,2.0,1.0,0.0,0.0
4622763,1.0,0.0,0,2.0,0,1.0,1.0,0.0,1.0,0.0,...,1.0,1.0,0.0,0.0,0.0,1.0,2.0,2.0,1.0,0.0
2870611,0.0,0.0,0,2.0,0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
5854257,0.0,0.0,0,2.0,0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1107612,1.0,1.0,0,1.0,1,0.0,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0

In [ ]:
selected_snps_dataset = selected_snps_dataset.loc[:,~selected_snps_dataset.columns.duplicated()]

#### Matching subjects with working memory data

In [ ]:
label_file= '/data/users2/pnadigapusuresh1/Projects/ukbiobank/Data/subset_vars.csv'

In [ ]:
vars = pd.read_csv(label_file,index_col='eid',
                            usecols=['eid','maximum_digits_remembered_correctly_f4282_2_0',
                            'sex_f31_0_0','age_when_attended_assessment_centre_f21003_0_0'])

In [ ]:
vars.columns = ['sex','score','age']

In [ ]:
vars

         sex  score   age
eid
5230587  1.0    8.0  57.0
2369031  0.0    7.0  45.0
4304744  0.0    7.0  69.0
4373404  1.0    6.0  51.0
1229224  1.0    8.0  60.0
...      ...    ...   ...
3001470  0.0    4.0  46.0
2677873  1.0    NaN  62.0
5343321  0.0    6.0  56.0
2504488  1.0    9.0  50.0
4348663  1.0    7.0  64.0

[39760 rows x 3 columns]

In [ ]:
vars = vars.loc[vars.score.isin([2,3,4,5,9,10,11,12])]

In [ ]:
selected_snps_dataset

,rs11235827,rs10898940,rs67259239,rs1670546,rs76332820,rs72982970,rs4944873,rs146217454,rs41311857,rs72985970,...,rs75332038,rs310434,rs6794101,rs2662764,rs77980659,rs4447797,rs13062950,rs34390533,rs9839511,rs145914525
FID,,,,,,,,,,,,,,,,,,,,,
1767364,0.0,2.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2268235,1.0,2.0,0,0.0,0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0
4521147,0.0,2.0,0,0.0,0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
5278224,0.0,0.0,0,2.0,0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,2.0,1.0,1.0,0.0
1925234,2.0,0.0,1,2.0,0,1.0,2.0,NaN,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4283752,0.0,2.0,0,0.0,1,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,2.0,2.0,1.0,0.0,0.0
4622763,1.0,0.0,0,2.0,0,1.0,1.0,0.0,1.0,0.0,...,1.0,1.0,0.0,0.0,0.0,1.0,2.0,2.0,1.0,0.0
2870611,0.0,0.0,0,2.0,0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
5854257,0.0,0.0,0,2.0,0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1107612,1.0,1.0,0,1.0,1,0.0,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0

In [ ]:
subjects_with_working_mem_and_gene = set(vars.index.tolist()).intersection(selected_snps_dataset.index.tolist())

In [ ]:
gene_working_mem = selected_snps_dataset.loc[list(subjects_with_working_mem_and_gene)]

In [ ]:
gene_working_mem

,rs11235827,rs10898940,rs67259239,rs1670546,rs76332820,rs72982970,rs4944873,rs146217454,rs41311857,rs72985970,...,rs75332038,rs310434,rs6794101,rs2662764,rs77980659,rs4447797,rs13062950,rs34390533,rs9839511,rs145914525
FID,,,,,,,,,,,,,,,,,,,,,
2588677,0.0,1.0,0,1.0,0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0
3670029,1.0,2.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0
1245201,0.0,2.0,0,0.0,1,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
2162713,0.0,1.0,0,1.0,0,1.0,2.0,0.0,NaN,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5636125,0.0,1.0,0,0.0,0,1.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4259788,0.0,0.0,0,0.0,0,2.0,2.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0
5275598,0.0,1.0,0,0.0,0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3243989,0.0,1.0,0,1.0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
1343446,0.0,1.0,0,0.0,0,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,2.0,1.0,0.0,1.0
1671167,2.0,1.0,1,1.0,0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [ ]:
vars

         sex  score   age
eid
2325525  0.0    5.0  50.0
4497030  0.0    3.0  63.0
6006365  0.0    5.0  41.0
3068829  1.0    5.0  57.0
1343142  0.0    5.0  55.0
...      ...    ...   ...
5609154  0.0   10.0  45.0
1764773  1.0    4.0  68.0
4165735  1.0    5.0  64.0
3001470  0.0    4.0  46.0
2504488  1.0    9.0  50.0

[5469 rows x 3 columns]

In [ ]:
gene_working_mem.to_csv('gene_working_mem_dataset.csv')

In [ ]:
gene_working_mem = gene_working_mem.fillna(0)

In [ ]:
gene_working_mem

,rs11235827,rs10898940,rs67259239,rs1670546,rs76332820,rs72982970,rs4944873,rs146217454,rs41311857,rs72985970,...,rs75332038,rs310434,rs6794101,rs2662764,rs77980659,rs4447797,rs13062950,rs34390533,rs9839511,rs145914525
FID,,,,,,,,,,,,,,,,,,,,,
2588677,0.0,1.0,0,1.0,0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0
3670029,1.0,2.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0
1245201,0.0,2.0,0,0.0,1,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
2162713,0.0,1.0,0,1.0,0,1.0,2.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5636125,0.0,1.0,0,0.0,0,1.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4259788,0.0,0.0,0,0.0,0,2.0,2.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0
5275598,0.0,1.0,0,0.0,0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3243989,0.0,1.0,0,1.0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
1343446,0.0,1.0,0,0.0,0,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,2.0,1.0,0.0,1.0
1671167,2.0,1.0,1,1.0,0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [ ]:
pd.read_csv('gene_working_mem_dataset.csv',index_col='FID')

,rs11235827,rs10898940,rs67259239,rs1670546,rs76332820,rs72982970,rs4944873,rs146217454,rs41311857,rs72985970,...,rs75332038,rs310434,rs6794101,rs2662764,rs77980659,rs4447797,rs13062950,rs34390533,rs9839511,rs145914525
FID,,,,,,,,,,,,,,,,,,,,,
2588677,0.0,1.0,0,1.0,0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0
3670029,1.0,2.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0
1245201,0.0,2.0,0,0.0,1,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
2162713,0.0,1.0,0,1.0,0,1.0,2.0,0.0,NaN,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5636125,0.0,1.0,0,0.0,0,1.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4259788,0.0,0.0,0,0.0,0,2.0,2.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0
5275598,0.0,1.0,0,0.0,0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3243989,0.0,1.0,0,1.0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
1343446,0.0,1.0,0,0.0,0,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,2.0,1.0,0.0,1.0
1671167,2.0,1.0,1,1.0,0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [ ]:
vars = vars.loc[gene_working_mem.index.tolist()]

In [ ]:
vars.iloc[200]

sex       0.0
score     4.0
age      53.0
Name: 4228319, dtype: float64

In [ ]:
gene_working_mem.iloc[200].to_numpy()

array([0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 2., 1., 1., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 2., 2., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1.,
       0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 2., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 2., 0., 0., 1.,
       1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 2.,
       0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 1., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 2., 0., 0., 1., 0., 1.,
       0., 1., 0., 0., 1., 0., 2., 0., 0., 0., 1., 1., 0., 0., 0., 2., 0.,
       0., 0., 1., 0., 2., 0., 2., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 2., 1., 1., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 1., 1., 2., 0., 0., 0., 2., 0., 0., 1., 1., 0., 0., 0.,
       1., 0., 1., 2., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1.,
       0., 1., 0., 0., 2., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       1., 1., 0., 2., 0., 0., 0., 0., 0., 1., 1., 0., 0., 2., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 2., 0., 2., 1.,
       1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       1., 0., 0., 2., 2., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1.,
       0., 0., 0., 1., 2., 0., 0., 0., 0., 0., 2., 0., 0., 0., 1., 2., 0.,
       1., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
import torch

In [ ]:
torch.tensor(gene_working_mem.iloc[200].to_numpy())

tensor([0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 2., 1., 1., 0., 0.,
        0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 2., 2., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1.,
        0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
        0., 1., 0., 0., 0., 2., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 2., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
        0., 1., 0., 1., 0., 0., 0., 0., 2., 0., 0., 2., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 2., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        1., 2., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 2., 0., 0., 0., 1.,
        1., 0., 0., 0., 2., 0., 0., 0., 1., 0., 2., 0., 2., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 2., 1., 1., 0., 0., 1.,
        0., 0., 0., 1., 0., 0., 0., 1., 1., 2., 0., 0., 0., 2., 0., 0., 1., 1.,
        0., 0., 0., 1., 0., 1., 2., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0.,
        0., 1., 0., 1., 0., 0., 2., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
        1., 1., 0., 2., 0., 0., 0., 0., 0., 1., 1., 0., 0., 2., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 2., 0., 2., 1., 1., 1.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0.,
        2., 2., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1.,
        2., 0., 0., 0., 0., 0., 2., 0., 0., 0., 1., 2., 0., 1., 0., 0., 1., 0.,
        0., 0., 0., 0.], dtype=torch.float64)

In [8]:
adj_matrix_second_third.values.sum()

2311